(() => {
 'use strict';
 const S=window.AdminStore,main=document.querySelector('main'),dialog=document.querySelector('dialog');
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const money=n=>n===null||n===undefined?'Unknown':new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:n%100?2:0}).format(n/100);
 const link=(to,label,cls='text-link')=>isAllowed(to.split('?')[0])?`<a href="#${esc(to)}" class="${cls}">${esc(label)}</a>`:`<span class="small">${esc(label)} · role access required</span>`;
 const button=(action,label,data={},cls='button')=>{const permission=({export:'finance',replacement:'finance','refund-approve':'finance','refund-edit':'finance','refund-submit':'finance','refund-verify':'finance',costs:'finance',progress:'work','job-sheet':'work',rework:'work','shipping-reconcile':'work','shipping-fallback':'work','art-publish':'settings','art-rollback':'settings','staff-revoke':'settings','automation-pause':'settings','automation-replay':'settings','owner-recover':null})[action];if(permission&&S.state.role!=='owner'&&(permission==='settings'||permission==='finance'||permission==='work'&&S.state.role!=='operations'))return '';return `<button type="button" class="${cls}" data-action="${esc(action)}" data-args="${esc(JSON.stringify(data))}">${esc(label)}</button>`;};
 const actions=(...x)=>`<div class="actions">${x.join('')}</div>`;
 const pill=(t,type='')=>`<span class="pill ${type}">${esc(t)}</span>`;
 const panel=(title,body,intro='')=>`<section class="panel"><h2>${esc(title)}</h2>${intro?`<p class="panel-sub">${esc(intro)}</p>`:''}${body}</section>`;
 const table=(title,heads,rows)=>`<div class="table-wrap" role="region" aria-label="${esc(title)}" tabindex="0"><table><caption>${esc(title)}</caption><thead><tr>${heads.map(h=>`<th scope="col">${h}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(v=>`<td>${v??'—'}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;
 const facts=rows=>`<dl class="definition">${rows.map(([a,b])=>`<div><dt>${esc(a)}</dt><dd>${b}</dd></div>`).join('')}</dl>`;
 const notice=(title,body,type='')=>`<section class="notice ${type}"><h2>${esc(title)}</h2><p>${body}</p></section>`;
 const empty=(title,body,to='orders',label='Return to Today')=>`<div class="empty"><h2>${esc(title)}</h2><p>${esc(body)}</p>${link(to,label)}</div>`;
 const field=(name,label,value='',type='text',hint='',required=true)=>`<label class="field"><span>${esc(label)}</span><input aria-label="${esc(label)}" name="${esc(name)}" type="${type}" value="${esc(value)}" ${required?'required':''} ${type==='number'?'step="any"':''}>${hint?`<small>${esc(hint)}</small>`:''}</label>`;
 const select=(name,label,options,value='')=>`<label class="field"><span>${esc(label)}</span><select aria-label="${esc(label)}" name="${esc(name)}">${options.map(o=>{const [v,t]=Array.isArray(o)?o:[o,o];return `<option value="${esc(v)}"${String(value)===String(v)?' selected':''}>${esc(t)}</option>`;}).join('')}</select></label>`;
 const textarea=(name,label,value='',required=true)=>`<label class="field"><span>${esc(label)}</span><textarea aria-label="${esc(label)}" name="${esc(name)}" ${required?'required':''}>${esc(value)}</textarea></label>`;
 const check=(name,label,checked=false)=>`<label class="check"><input name="${esc(name)}" type="checkbox"${checked?' checked':''}><span>${esc(label)}</span></label>`;
 const list=items=>`<ul class="list">${items.map(x=>`<li>${x}</li>`).join('')}</ul>`;
 const details=(title,body)=>`<details><summary>${esc(title)}</summary>${body}</details>`;
 const grid=(left,right)=>`<div class="grid"><div>${left}</div><aside>${right}</aside></div>`;
 const stat=(label,value,sub='')=>`<div class="stat"><span class="label">${esc(label)}</span><strong>${esc(value)}</strong><small>${esc(sub)}</small></div>`;
 const form=(name,body,submit='Save changes',data={})=>`<form data-form="${esc(name)}" data-args="${esc(JSON.stringify(data))}">${body}<div class="error-text" role="alert" hidden></div><div class="actions"><button class="button" type="submit">${esc(submit)}</button></div></form>`;
 const artImg=(id,cls='thumb')=>{const p=S.state.products.find(p=>p.id===id);return p?.image?`<img class="${cls}" src="${esc(p.image)}" alt="${esc(p.title)}" loading="lazy">`:'';};
 const areas={orders:'Orders',customers:'Customers',products:'Products',support:'Support',reports:'Reports',staff:'Staff & Access',connections:'Connections',settings:'Store setup',help:'Help & demo',search:'Search'};
 const tabs={};
 let route='orders',params=new URLSearchParams(),toastTimer,dialogOrigin,embedded=0;
 const screens={},handlers={},forms={},binders={};
 const isAllowed=r=>{const role=S.state.role;if(role==='owner')return true;if(['staff','connections','settings'].includes(r.split('/')[0])&&!['settings/recovery','settings/login'].includes(r))return false;if(r==='help')return true;if(r==='support'&&window.AdminUI?.params.get('view')==='refunds')return false;if(['settings/journeys','settings/readiness','settings/access','settings/recovery','settings/guides','tools','search'].includes(r))return true;if(r.startsWith('settings')||r.startsWith('orders/refund')||r.startsWith('orders/pay')||r.startsWith('orders/settle')||r==='orders/dispute'||r==='orders/document'||r==='orders/export'||r==='orders/replacement')return false;if(r.startsWith('reports'))return r==='reports/operations';if(r.startsWith('customers')||r.startsWith('support')||r==='orders/change')return role==='support';if(r.startsWith('products')||['orders/job','orders/production','orders/packing','orders/quality','orders/shipping','orders/parcel','orders/bulk'].includes(r))return role==='operations';return true;};
 const heading=(title,intro,body,buttons='')=>embedded?body+buttons:`<div class="page-heading"><div><h1 tabindex="-1">${esc(title)}</h1>${intro?`<p class="page-intro">${esc(intro)}</p>`:''}</div>${buttons}</div>${body}`;
 function context(name,values,fn){const oldRoute=route,oldParams=params;route=name;params=new URLSearchParams(values);embedded++;try{return fn();}finally{route=oldRoute;params=oldParams;embedded--;}}

 function toast(message,error=false){const el=document.querySelector('#toast');el.textContent=message;el.hidden=false;el.classList.toggle('error',error);clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.hidden=true,6500);}
 function modal(title,intro,body,onSubmit,submit='Confirm',danger=false){dialogOrigin=document.activeElement;dialog.innerHTML=`<div class="dialog-head"><div><p class="eyebrow">Studio workspace</p><h2 id="dialog-title">${esc(title)}</h2></div><button class="icon-button" type="button" data-close aria-label="Close dialog">×</button></div><div class="dialog-body"><p>${esc(intro)}</p><form id="modal-form">${body}<div class="error-text" id="modal-error" role="alert" hidden></div><div class="actions"><button type="button" class="button secondary" data-close>Cancel</button><button class="button ${danger?'danger':''}" type="submit">${esc(submit)}</button></div></form></div>`;dialog.querySelectorAll('select[name=owner]').forEach(el=>{const people=[S.names.owner,...(S.state.staff||[]).filter(p=>p.active).map(p=>p.name)];el.innerHTML=people.map(name=>`<option value="${esc(name)}">${name===S.names.owner?'You (Owner)':esc(name)}</option>`).join('');});dialog.showModal();dialog.querySelector('form').onsubmit=async e=>{e.preventDefault();if(e.target.dataset.busy)return;e.target.dataset.busy='1';const submitButton=e.target.querySelector('[type=submit]');submitButton.disabled=true;const data=Object.fromEntries(new FormData(e.target));try{await onSubmit(data,e.target);dialog.close();render();toast(S.storageError||'Saved in this browser. No live service was contacted.');}catch(err){const box=dialog.querySelector('#modal-error');box.textContent=err.message;box.hidden=false;box.tabIndex=-1;box.focus();}finally{delete e.target.dataset.busy;submitButton.disabled=false;}};dialog.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>dialog.close());}
 dialog.addEventListener('close',()=>{if(dialogOrigin?.isConnected)dialogOrigin.focus();});
 function download(filename,text,type='text/csv;charset=utf-8'){const blob=new Blob([text],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 function commit(id,action,fn,reason){S.mutate(id,action,fn,reason);render();toast(S.storageError||'Saved to the sample workspace.');}
 function orderContext(){const id=params.get('id')||'AS-1001',o=S.order(id),i=S.item(o,params.get('item'));return {o,i,id,item:i.id};}
 const orderUrl=(name,o,i)=>name+'?id='+encodeURIComponent(o.id)+(i?'&item='+encodeURIComponent(i.id):'');
 function scenario(){return `<div class="scenario-control"><label for="list-state">View example</label><select id="list-state"><option value="normal">Current records</option><option value="empty"${params.get('state')==='empty'?' selected':''}>Empty view</option><option value="error"${params.get('state')==='error'?' selected':''}>Loading error</option></select></div>`;}
 function queue(body){if(params.get('state')==='empty')return empty('No outstanding work in this view','Clear the example to return to current records.',route,'Show current records');if(params.get('state')==='error')return notice('We could not refresh this list','Your saved records are intact. '+link(route,'Retry loading records')+'. '+link('settings/system','Review owned service alerts')+'.','error');return body;}
 handlers.reset=()=>modal('Reset the sample workspace?','This replaces only Admin A1 demo changes in this browser. The public prototype and W1 reference are preserved.',list(['Six fictional orders and the approved catalogue are restored.','Use this to repeat the operating journey from the beginning.']),()=>{S.reset();location.hash='orders';},'Reset demo',true);
 handlers.export=({kind='orders'}={})=>{S.guard('export');modal('Export sample '+kind,'This download contains fictional demo records. Live exports will require server permissions and expiring authorised access.',select('kind','Record type',['orders','products','cases','finance'],kind),d=>{let rows;const s=S.state;if(d.kind==='products')rows=[['artwork_id','title','status','version'],...s.products.map(p=>[p.id,p.title,p.status,p.version])];else if(d.kind==='cases')rows=[['case_id','order_id','subject','source','owner','status'],...s.cases.map(c=>[c.id,c.order,c.subject,c.source,c.owner,c.status])];else if(d.kind==='finance')rows=[['order_id','currency','captured_paise','completed_refunds_paise','bank_matched','replacement'],...s.orders.map(o=>[o.id,o.currency,o.payment==='Captured'?o.total:0,o.refunds.filter(r=>r.status==='Completed').reduce((a,r)=>a+r.amount,0),o.bankMatched,o.replacement])];else rows=[['order_id','customer_id','currency','total_paise','payment','fulfilment','original_promise','current_promise'],...s.orders.filter(o=>matchesOrder(o)).map(o=>[o.id,o.customer,o.currency,o.total,o.payment,S.summary(o),o.originalDue,o.due])];S.mutate('EXPORT',d.kind+' export',()=>{});download('aalishaan-demo-'+d.kind+'.csv',S.csv(rows));},'Download sample CSV');};
 const matchesOrder=o=>{const f=S.state.filters,c=S.state.customers.find(c=>c.id===o.customer);return (f.owner==='All'||o.owner===f.owner)&&(f.status==='All'||(f.status==='Needs attention'?(o.hold||o.payment!=='Captured'||o.items.some(i=>i.quality==='Failed')||S.state.tasks.some(t=>t.record===o.id&&t.status!=='Resolved')):S.summary(o)===f.status))&&[o.id,c?.name,...o.items.map(i=>i.title)].join(' ').toLowerCase().includes(f.q.toLowerCase());};
 function render(){if(window.AdminUI?.beforeRender&&!window.AdminUI.beforeRender())return;let raw=location.hash.slice(1)||'orders';const canonical=window.AdminUI?.canonical?.(raw);if(canonical&&canonical!==raw){history.replaceState(null,'','#'+canonical);raw=canonical;}const [name,query='']=raw.split('?');route=name;params=new URLSearchParams(query);if(dialog.open)dialog.close();const roleControl=document.querySelector('#role-select');if(roleControl)roleControl.value=S.state.role;const active=route.split('/')[0];
  document.querySelector('#navigation').innerHTML=['orders','customers','products','support','reports','staff','connections'].filter(a=>isAllowed(a)||(a==='reports'&&isAllowed('reports/operations'))).map(a=>`<a href="#${a==='reports'&&S.state.role!=='owner'?'reports/operations':a}"${active===a?' aria-current="page"':''}><span class="nav-icon" aria-hidden="true">${window.StudioIcons?.[a]||''}</span><span>${areas[a]}</span></a>`).join('');document.querySelector('#settings-navigation').innerHTML='';
  let body;try{if(!S.state.signedIn||S.state.revoked.includes(S.state.role))body=screens['settings/login']();else if(!isAllowed(route))body=heading('Access restricted','This role preview cannot open this record or action.',notice('Return to permitted work','Operations handles jobs and parcels; Support handles cases and customer history. Finance and access changes belong to the owner. This is a UI demonstration; real server authorisation is future implementation.','warn')+link('orders','Return to Today','button'));else body=screens[route]?screens[route]():heading('Page not found','This record or destination is not available.',empty('Let’s get you back to the studio','Use the menu or search for an original record.'));}catch(e){body=heading('Record unavailable',e.message,link('orders/all','Return to All orders','button secondary'));}
  const area=route.split('/')[0];main.innerHTML=(S.state.signedIn&&tabs[area]&&isAllowed(route)?`<nav class="section-tabs" aria-label="${areas[area]} pages">${tabs[area].filter(([r])=>isAllowed(r)).map(([r,label])=>`<a href="#${r}"${r===route?' aria-current="page"':''}>${label}</a>`).join('')}</nav>`:'')+body;
  if(S.storageError)main.insertAdjacentHTML('afterbegin',notice('Browser storage notice',esc(S.storageError),'warn'));
  const view=main.querySelector('#list-state');if(view)view.onchange=()=>{const p=new URLSearchParams(params);p.set('state',view.value);location.hash=route+'?'+p;};binders[route]?.();document.title=(main.querySelector('h1')?.textContent||'Admin')+' · Aalishaan Studio A1';window.AdminUI?.afterRender?.();closeMenu();}
 document.addEventListener('click',async e=>{const b=e.target.closest('[data-action]');if(!b)return;try{const data=JSON.parse(b.dataset.args||'{}'),handler=handlers[b.dataset.action];if(!handler)throw Error('This action is unavailable. Reload the prototype.');if(b.dataset.busy)return;b.dataset.busy='1';b.disabled=true;try{await handler(data,b);}finally{delete b.dataset.busy;b.disabled=false;}}catch(err){toast(err.message,true);}});
 document.addEventListener('submit',async e=>{const f=e.target.closest('[data-form]');if(!f)return;e.preventDefault();if(f.dataset.busy)return;f.dataset.busy='1';const submit=f.querySelector('button[type=submit]');if(submit)submit.disabled=true;const box=f.querySelector('[role="alert"]');try{await forms[f.dataset.form](Object.fromEntries(new FormData(f)),JSON.parse(f.dataset.args||'{}'),f);if(f.isConnected)box.hidden=true;}catch(err){box.textContent=err.message;box.hidden=false;box.tabIndex=-1;box.focus();}finally{delete f.dataset.busy;if(submit)submit.disabled=false;}});
 document.querySelector('#global-search').onsubmit=e=>{e.preventDefault();location.hash='search?q='+encodeURIComponent(document.querySelector('#record-search').value.trim());};
 const sidebar=document.querySelector('#sidebar'),menuToggle=document.querySelector('#menu-toggle'),phoneMenu=window.matchMedia('(max-width:700px)');
 function syncMenu(){const opened=phoneMenu.matches&&sidebar.classList.contains('open');sidebar.inert=phoneMenu.matches&&!opened;menuToggle.setAttribute('aria-expanded',String(opened));}
 function closeMenu(restoreFocus=false){const opened=sidebar.classList.contains('open');sidebar.classList.remove('open');syncMenu();if(opened&&restoreFocus)menuToggle.focus();}
 menuToggle.onclick=()=>{if(sidebar.classList.contains('open'))closeMenu(true);else{sidebar.classList.add('open');syncMenu();sidebar.querySelector('[aria-current=page],a')?.focus();}};
 phoneMenu.addEventListener('change',()=>{const focused=sidebar.contains(document.activeElement);closeMenu(focused&&phoneMenu.matches);});
 document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!dialog.open)closeMenu(true);});
 document.addEventListener('click',e=>{if(phoneMenu.matches&&!sidebar.contains(e.target)&&!menuToggle.contains(e.target))closeMenu();});
 document.querySelector('.skip').onclick=e=>{e.preventDefault();main.focus();main.scrollIntoView({block:'start'});};
 syncMenu();
 document.querySelector('#role-select').onchange=e=>{try{S.setRole(e.target.value);render();toast('Role preview changed. These local controls do not provide real authentication.');}catch(err){toast(err.message,true);}};
 window.addEventListener('hashchange',render);window.addEventListener('storage',e=>{if(e.key===S.KEY)toast('Another tab changed this demo. Reload before saving to avoid overwriting its work.',true);});
 window.AdminUI={context,S,esc,money,link,button,actions,pill,panel,table,facts,notice,empty,field,select,textarea,check,list,details,grid,stat,form,artImg,heading,modal,download,commit,orderContext,orderUrl,scenario,queue,screens,handlers,forms,binders,toast,render,isAllowed,matchesOrder,get route(){return route;},get params(){return params;}};
 document.addEventListener('DOMContentLoaded',render);
})();
