/* Local files only. No upload endpoint, provider secrets, or public-site writes.
 * Print contents use AES-GCM at rest. This is not server authentication or a
 * protection boundary against untrusted scripts running on the same origin.
 */
(() => {
  'use strict';
  const DB_NAME='aalishaan-admin-a2-files', encoder=new TextEncoder(), decoder=new TextDecoder();
  let db, key=null, config=null, publicItems=[], privateItems=[], lockTimer, urls=new Map();
  const MAX_PRIVATE=100*1024*1024, MAX_PUBLIC=25*1024*1024, MAX_BACKUP=512*1024*1024;
  const b64 = bytes => {let s='';for(let i=0;i<bytes.length;i+=16384)s+=String.fromCharCode(...bytes.subarray(i,i+16384));return btoa(s);};
  const un64 = s => Uint8Array.from(atob(s),x=>x.charCodeAt(0));
  const id = () => crypto.randomUUID ? crypto.randomUUID() : b64(crypto.getRandomValues(new Uint8Array(18))).replace(/[^a-z0-9]/gi,'');
  const hex = buffer => [...new Uint8Array(buffer)].map(x=>x.toString(16).padStart(2,'0')).join('');
  function requireCrypto(){if(!crypto?.subtle)throw Error('Open this admin over HTTPS or localhost to use the encrypted vault.');}
  function transaction(stores, mode, fn) { return new Promise((resolve,reject)=>{const tx=db.transaction(stores,mode);let result;try{result=fn(tx);}catch(e){tx.abort();reject(e);return;}tx.oncomplete=()=>resolve(result);tx.onerror=()=>reject(tx.error||Error('Local storage failed. Keep your original files.'));tx.onabort=()=>reject(tx.error||Error('Local file transaction did not complete.'));}); }
  function get(store,k){return new Promise((resolve,reject)=>{const req=db.transaction(store).objectStore(store).get(k);req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});}
  async function metadata(store){return new Promise((resolve,reject)=>{const out=[],req=db.transaction(store).objectStore(store).openCursor();req.onsuccess=()=>{const c=req.result;if(!c){resolve(out);return;}const {data,original,preview,...meta}=c.value;out.push({...meta,preview});c.continue();};req.onerror=()=>reject(req.error);});}
  async function refresh(){publicItems=await metadata('public');privateItems=await metadata('private');for(const u of urls.values())URL.revokeObjectURL(u);urls.clear();for(const x of publicItems)if(x.preview)urls.set(x.id,URL.createObjectURL(x.preview));config=await get('meta','vault');}
  const ready=new Promise((resolve,reject)=>{if(!window.indexedDB){reject(Error('Local file storage is unavailable in this browser.'));return;}const request=indexedDB.open(DB_NAME,1);request.onupgradeneeded=()=>{for(const name of ['public','private','meta'])if(!request.result.objectStoreNames.contains(name))request.result.createObjectStore(name,{keyPath:'id'});};request.onsuccess=async()=>{db=request.result;db.onversionchange=()=>{db.close();lock();};try{await refresh();resolve();}catch(e){reject(e);}};request.onerror=()=>reject(request.error||Error('Could not open local file storage.'));request.onblocked=()=>reject(Error('Close the other admin tabs and try again.'));});
  // Attach a rejection observer immediately; callers still receive failures.
  ready.catch(()=>{});
  async function capacity(bytes){if(navigator.storage?.estimate){const e=await navigator.storage.estimate();if(e.quota&&e.usage+bytes>e.quota*.94)throw Error('Not enough browser storage. Back up files, free space, and retry.');}}
  async function persist(){await ready;return navigator.storage?.persist?await navigator.storage.persist():false;}
  async function derive(password,salt){requireCrypto();const base=await crypto.subtle.importKey('raw',encoder.encode(password),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations:600000,hash:'SHA-256'},base,{name:'AES-GCM',length:256},false,['encrypt','decrypt']);}
  function touch(){clearTimeout(lockTimer);if(key)lockTimer=setTimeout(()=>{lock();window.AdminUI?.toast('Private vault locked after 15 minutes without private-file activity.');if(!window.AdminUI?.hasDirty?.())window.AdminUI?.render();},15*60*1000);}
  function lock(){key=null;clearTimeout(lockTimer);}
  async function unlock(password,confirmation){await ready;requireCrypto();if(!config){if(password.length<12)throw Error('Use a passphrase of at least 12 characters.');if(password!==confirmation)throw Error('The passphrases do not match.');const salt=crypto.getRandomValues(new Uint8Array(16)),iv=crypto.getRandomValues(new Uint8Array(12)),candidate=await derive(password,salt);const verifier=await crypto.subtle.encrypt({name:'AES-GCM',iv,additionalData:encoder.encode('aalishaan-vault-v1')},candidate,encoder.encode('AALISHAAN_PRIVATE_VAULT_V1'));const next={id:'vault',version:1,iterations:600000,salt:b64(salt),iv:b64(iv),verifier:b64(new Uint8Array(verifier))};await transaction(['meta'],'readwrite',tx=>tx.objectStore('meta').put(next));config=next;key=candidate;}else{try{const candidate=await derive(password,un64(config.salt));const value=await crypto.subtle.decrypt({name:'AES-GCM',iv:un64(config.iv),additionalData:encoder.encode('aalishaan-vault-v1')},candidate,un64(config.verifier));if(decoder.decode(value)!=='AALISHAAN_PRIVATE_VAULT_V1')throw Error();key=candidate;}catch{throw Error('The passphrase is incorrect, or this vault is damaged. No files were changed.');}}touch();}
  function aad(record){return encoder.encode([record.id,record.product,record.kind,record.version].join('|'));}
  async function addPrivate(file,{product,version,kind='print',note=''}){await ready;if(!key)throw Error('Unlock the private vault first.');if(!file?.size)throw Error('Choose a non-empty file.');if(file.size>MAX_PRIVATE)throw Error('The local prototype accepts private files up to 100 MB each. Keep larger masters in your original storage.');if(!/\.(pdf|tiff?|png|jpe?g|webp|psd|psb|ai|eps|zip)$/i.test(file.name))throw Error('Use PDF, TIFF, PSD/PSB, AI/EPS, ZIP, PNG, JPEG or WebP.');if(!/^v[1-9]\d*$/.test(version))throw Error('Use a file version such as v3 or v4.');if(!['print','approval'].includes(kind))throw Error('Unknown private file category.');if(kind==='print'&&privateItems.some(x=>x.product===product&&x.kind==='print'&&x.version===version))throw Error('That print version already exists. Use a new version; released jobs keep the original.');await capacity(file.size*1.1);const iv=crypto.getRandomValues(new Uint8Array(12));const record={id:id(),product,version,kind,note:String(note).slice(0,2000),name:file.name,size:file.size,type:file.type||'application/octet-stream',created:new Date().toISOString(),iv:b64(iv)};const original=await file.arrayBuffer();record.sha=hex(await crypto.subtle.digest('SHA-256',original));record.data=await crypto.subtle.encrypt({name:'AES-GCM',iv,additionalData:aad(record)},key,original);await transaction(['private'],'readwrite',tx=>tx.objectStore('private').add(record));await refresh();touch();return privateItems.find(x=>x.id===record.id);}
  async function privateBlob(fileId){await ready;if(!key)throw Error('Unlock the private vault first.');const record=await get('private',fileId);if(!record)throw Error('This original file is not present in this browser. Restore its file backup.');try{const bytes=await crypto.subtle.decrypt({name:'AES-GCM',iv:un64(record.iv),additionalData:aad(record)},key,record.data);if(hex(await crypto.subtle.digest('SHA-256',bytes))!==record.sha)throw Error();touch();return {blob:new Blob([bytes],{type:record.type}),record};}catch{throw Error('The file could not be verified. No altered print file was downloaded. Restore your original backup.');}}
  function download(blob,name){const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=name;a.rel='noopener';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),60000);}
  async function downloadPrivate(fileId){const x=await privateBlob(fileId);download(x.blob,x.record.name);}
  async function imageBlob(original,{width=1600,type='image/webp',quality=.9}={}){let bitmap;try{bitmap=await createImageBitmap(original);}catch{throw Error('This file cannot be decoded as an image. Choose a valid PNG, JPEG or WebP.');}const factor=Math.min(1,width/Math.max(bitmap.width,bitmap.height)),canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(bitmap.width*factor));canvas.height=Math.max(1,Math.round(bitmap.height*factor));const ctx=canvas.getContext('2d');ctx.drawImage(bitmap,0,0,canvas.width,canvas.height);const dimensions={width:bitmap.width,height:bitmap.height};bitmap.close();const blob=await new Promise(resolve=>canvas.toBlob(resolve,type,quality));canvas.width=canvas.height=1;if(!blob)throw Error('Image processing failed. The existing image was preserved.');return {blob,...dimensions};}
  async function addPublic(file,{id:slotId,product='',slot='',alt='',general=false}){await ready;if(!file?.size||file.size>MAX_PUBLIC)throw Error('Choose a PNG, JPEG or WebP up to 25 MB.');if(!['image/png','image/jpeg','image/webp'].includes(file.type)||!/\.(png|jpe?g|webp)$/i.test(file.name))throw Error('Public images must be PNG, JPEG or WebP. Private print masters and SVG files are not accepted here.');await capacity(file.size*1.5);const processed=await imageBlob(file);if(processed.width<100||processed.height<100)throw Error('This image is too small. Use an image at least 100 pixels on both sides.');const record={id:slotId,product,slot,general,alt:String(alt).trim(),name:file.name,size:file.size,type:file.type,created:new Date().toISOString(),width:processed.width,height:processed.height,original:file,preview:processed.blob};await transaction(['public'],'readwrite',tx=>tx.objectStore('public').put(record));await refresh();return publicItems.find(x=>x.id===slotId);}
  async function removePublic(slotId){await ready;await transaction(['public'],'readwrite',tx=>tx.objectStore('public').delete(slotId));await refresh();}
  async function removePrivate(fileId){await ready;if(!key)throw Error('Unlock the private vault first.');await transaction(['private'],'readwrite',tx=>tx.objectStore('private').delete(fileId));await refresh();touch();}
  async function downloadPublic(slotId){const r=await get('public',slotId);if(!r)throw Error('Upload a local image first.');download(r.original,r.name);}
  // A small, dependency-free ZIP writer/reader for our own uncompressed backups.
  const crcTable=Array.from({length:256},(_,n)=>{let c=n;for(let j=0;j<8;j++)c=c&1?0xedb88320^(c>>>1):c>>>1;return c>>>0;});
  function crcBytes(bytes,c=0xffffffff){for(let j=0;j<bytes.length;j++)c=crcTable[(c^bytes[j])&255]^(c>>>8);return c;}
  async function crcBlob(blob){let crc=0xffffffff;for(let at=0;at<blob.size;at+=4*1024*1024)crc=crcBytes(new Uint8Array(await blob.slice(at,at+4*1024*1024).arrayBuffer()),crc);return (crc^0xffffffff)>>>0;}
  function safePath(path){return typeof path==='string'&&path.length>0&&!path.startsWith('/')&&!path.includes('\\')&&!path.split('/').some(x=>x==='..'||x==='')&&!/[\x00-\x1f]/.test(path);}
  async function zip(entries){const chunks=[],directory=[];let offset=0;const dt=new Date(),dosDate=((dt.getFullYear()-1980)<<9)|((dt.getMonth()+1)<<5)|dt.getDate(),dosTime=(dt.getHours()<<11)|(dt.getMinutes()<<5)|(dt.getSeconds()>>1);for(const entry of entries){if(!safePath(entry.name))throw Error('An unsafe export path was blocked.');const name=encoder.encode(entry.name),blob=entry.blob instanceof Blob?entry.blob:new Blob([entry.blob]);if(offset+blob.size>0xffffffff)throw Error('This export is too large for the local ZIP format.');const crc=await crcBlob(blob),header=new Uint8Array(30+name.length),view=new DataView(header.buffer);view.setUint32(0,0x04034b50,true);view.setUint16(4,20,true);view.setUint16(6,0x800,true);view.setUint16(10,dosTime,true);view.setUint16(12,dosDate,true);view.setUint32(14,crc,true);view.setUint32(18,blob.size,true);view.setUint32(22,blob.size,true);view.setUint16(26,name.length,true);header.set(name,30);chunks.push(header,blob);const central=new Uint8Array(46+name.length),cv=new DataView(central.buffer);cv.setUint32(0,0x02014b50,true);cv.setUint16(4,20,true);cv.setUint16(6,20,true);cv.setUint16(8,0x800,true);cv.setUint16(12,dosTime,true);cv.setUint16(14,dosDate,true);cv.setUint32(16,crc,true);cv.setUint32(20,blob.size,true);cv.setUint32(24,blob.size,true);cv.setUint16(28,name.length,true);cv.setUint32(42,offset,true);central.set(name,46);directory.push(central);offset+=header.length+blob.size;}const dirSize=directory.reduce((a,x)=>a+x.length,0),end=new Uint8Array(22),ev=new DataView(end.buffer);ev.setUint32(0,0x06054b50,true);ev.setUint16(8,entries.length,true);ev.setUint16(10,entries.length,true);ev.setUint32(12,dirSize,true);ev.setUint32(16,offset,true);return new Blob([...chunks,...directory,end],{type:'application/zip'});}
  async function unzip(file){if(file.size>MAX_BACKUP)throw Error('This prototype restores backups up to 512 MB.');const bytes=new Uint8Array(await file.arrayBuffer()),view=new DataView(bytes.buffer),entries=new Map();let offset=0;while(offset+30<=bytes.length&&view.getUint32(offset,true)===0x04034b50){if(entries.size>1500)throw Error('The backup contains too many files.');const flags=view.getUint16(offset+6,true),method=view.getUint16(offset+8,true),crc=view.getUint32(offset+14,true),length=view.getUint32(offset+18,true),nameLength=view.getUint16(offset+26,true),extra=view.getUint16(offset+28,true);if(method!==0||(flags&9))throw Error('Use an original unmodified backup exported by this admin.');const name=decoder.decode(bytes.subarray(offset+30,offset+30+nameLength)),start=offset+30+nameLength+extra,end=start+length;if(!safePath(name)||entries.has(name)||end>bytes.length)throw Error('Invalid or duplicate backup entry.');const payload=bytes.subarray(start,end);if(((crcBytes(payload)^0xffffffff)>>>0)!==crc)throw Error('The backup is damaged. No data was restored.');entries.set(name,new Blob([payload]));offset=end;}if(offset+4>bytes.length||view.getUint32(offset,true)!==0x02014b50)throw Error('This is not a valid admin backup.');return entries;}
  async function exportBackup(state){await ready;const entries=[],manifest={format:'aalishaan-admin-a2-backup',version:1,created:new Date().toISOString(),vault:config||null,public:[],private:[]};for(const meta of publicItems){const r=await get('public',meta.id),{original,preview,...m}=r;m.path='public/'+r.id.replace(/[^a-z0-9_-]/gi,'_')+'.bin';manifest.public.push(m);entries.push({name:m.path,blob:original});}for(const meta of privateItems){const r=await get('private',meta.id),{data,...m}=r;m.path='encrypted/'+r.id+'.bin';manifest.private.push(m);entries.push({name:m.path,blob:new Blob([data])});}entries.push({name:'manifest.json',blob:JSON.stringify(manifest)},{name:'admin-state.json',blob:JSON.stringify(state)},{name:'READ-ME.txt',blob:'Keep this backup outside the public repository. Private print contents remain encrypted and require your vault passphrase. Public images and fictional admin records are not encrypted. Restore through Staff & Access > Backups. Never commit this archive to your website.'});if(entries.reduce((a,x)=>a+(x.blob.size||x.blob.length||0),0)>MAX_BACKUP)throw Error('This combined backup exceeds 512 MB. Download your originals separately before clearing any storage.');return zip(entries);}
  function rejectDangerousKeys(x){if(x&&typeof x==='object')for(const [k,v] of Object.entries(x)){if(['__proto__','constructor','prototype'].includes(k))throw Error('Unsafe backup metadata.');rejectDangerousKeys(v);}}
  async function inspectBackup(file){await ready;const entries=await unzip(file);if(!entries.has('manifest.json')||!entries.has('admin-state.json'))throw Error('Choose a backup exported by this admin.');const manifest=JSON.parse(await entries.get('manifest.json').text()),state=JSON.parse(await entries.get('admin-state.json').text());rejectDangerousKeys(manifest);rejectDangerousKeys(state);if(manifest.format!=='aalishaan-admin-a2-backup'||manifest.version!==1||state.schema!==1||!Array.isArray(state.orders)||!Array.isArray(state.products)||!Array.isArray(state.customers)||!Array.isArray(state.cases)||!Array.isArray(state.audit))throw Error('This backup format is not supported.');const pub=[],priv=[];if(manifest.vault&&(manifest.vault.version!==1||manifest.vault.iterations!==600000||!manifest.vault.salt||!manifest.vault.verifier))throw Error('Unsupported vault configuration.');for(const m of manifest.public){const original=entries.get(m.path);if(!original||original.size!==m.size)throw Error('A public image is missing from this backup.');const image=await imageBlob(original);pub.push({...m,original:new Blob([original],{type:m.type}),preview:image.blob});}for(const m of manifest.private){const blob=entries.get(m.path);if(!blob||blob.size!==m.size+16||!m.iv||!m.sha||!m.id||!m.product)throw Error('An encrypted file is missing or invalid.');priv.push({...m,data:await blob.arrayBuffer()});}if(priv.length&&!manifest.vault)throw Error('The backup has private files but no vault key configuration.');return {state,manifest,pub,priv};}
  async function restoreFiles(checked){await ready;await transaction(['public','private','meta'],'readwrite',tx=>{for(const s of ['public','private','meta'])tx.objectStore(s).clear();checked.pub.forEach(x=>tx.objectStore('public').put(x));checked.priv.forEach(x=>tx.objectStore('private').put(x));if(checked.manifest.vault)tx.objectStore('meta').put(checked.manifest.vault);});lock();await refresh();}
  async function exportShared(){await ready;const entries=[];for(const slot of window.AdminSharedImages){const meta=publicItems.find(x=>x.id===slot.id&&x.general);if(!meta)continue;const r=await get('public',meta.id);for(const raw of slot.targets){const name=decodeURIComponent(raw);if(!name.startsWith('assets/')||!safePath(name))throw Error('Invalid approved asset path.');const ext=name.split('.').pop().toLowerCase(),type=ext==='png'?'image/png':ext==='webp'?'image/webp':ext==='jpg'||ext==='jpeg'?'image/jpeg':null;if(!type)throw Error('Unsupported target image format.');const image=await imageBlob(r.original,{width:type==='image/webp'?1600:10000,type,quality:.94});entries.push({name,blob:image.blob});}}
    if(!entries.length)throw Error('Upload at least one general image before exporting.');entries.push({name:'GENERAL-IMAGES-READ-ME.txt',blob:'These are only your uploaded PUBLIC general images, mapped to the existing approved asset filenames. Back up your repo, then merge the assets folder into the repository root and redeploy as usual. No source-code editing is needed. Existing product data and all private files are excluded. This download does not publish anything automatically.'});return zip(entries);}
  window.StudioMedia={ready,refresh,persist,unlock,lock,addPrivate,privateBlob,downloadPrivate,addPublic,removePublic,removePrivate,downloadPublic,exportBackup,inspectBackup,restoreFiles,exportShared,zip,download,imageBlob,get isUnlocked(){return !!key;},get hasVault(){return !!config;},get publicItems(){return publicItems;},get privateItems(){return privateItems;},url:k=>urls.get(k)||'',get:async(s,k)=>{await ready;return get(s,k);}};
  window.addEventListener('pagehide',lock);
})();
