/* A1 local simulation. No authentication, APIs, secrets or live customer records. */
(() => {
 'use strict';
 const KEY='aalishaan-admin-a1-v1', clone=x=>JSON.parse(JSON.stringify(x));
 const stages=['Pending payment','Paid & confirmed','Ready to make','Printing','Framing','Quality checked','Packed','Pickup booked','Shipped','Out for delivery','Delivered'];
 const names={owner:'Khalid',operations:'Asha',support:'Rahul'};
 const now=()=>new Date().toISOString();
 const art=slug=>window.AdminCatalogue.find(x=>x.slug.includes(slug));
 function fresh(){
  const product=(slug,frame='black',stage=0)=>({id:'LI-1',artId:art(slug).id,title:art(slug).title,frame,qty:1,price:art(slug).prices[frame],stage,file:'v3',reserved:stage>=2,consumed:stage>=3,quality:stage>=5?'Passed':'Not inspected',inspections:[],evidence:[],packing:stage>=6?{weight:4.2,length:72,width:54,height:9,version:'PACK-DEMO-1',photo:'Sample parcel evidence',checks:true}:null,parcel:stage>=7?{id:'',status:stages[stage],awb:'',shiprocketOrder:'',shiprocketShipment:'',history:[]}:null});
  const orders=[
   {id:'AS-1001',customer:'C-1001',items:[product('lantern-that')],payment:'Pending',paymentResult:'Captured',owner:'Asha',due:'2026-09-18',note:'',hold:false},
   {id:'AS-1002',customer:'C-1002',items:[product('bridge-of-blue','white')],payment:'Unknown',paymentResult:'Unknown',owner:'Khalid',due:'2026-09-17',note:'Browser closed after payment. Verify the existing attempt.',hold:false},
   {id:'AS-1003',customer:'C-1003',items:[product('lantern-that','black',10),{...product('palace-above','black',3),id:'LI-2'}],payment:'Captured',owner:'Asha',due:'2026-09-17',note:'Two artworks. Preserve item context on every delivery update.',hold:false},
   {id:'AS-1004',customer:'C-1004',items:[product('pine-that','antique-gold',10)],payment:'Captured',owner:'Rahul',due:'2026-09-12',note:'Customer reports a marked frame after delivery.',hold:false},
   {id:'AS-1005',customer:'C-1005',items:[product('bridge-of-blue','black',2)],payment:'Captured',owner:'Asha',due:'2026-09-18',note:'Cancellation request received before printing.',hold:true},
   {id:'AS-1006',customer:'C-1006',items:[product('teahouse-shutters','white',4)],payment:'Captured',owner:'Asha',due:'2026-09-12',note:'Frame corner requires rework.',hold:false}
  ].map((o,n)=>({...o,version:1,total:o.items.reduce((s,i)=>s+i.qty*i.price,0),currency:'INR',originalDue:o.due,address:'Sample address, Mumbai 400001',purchaseAddress:'Sample address, Mumbai 400001',policy:'POLICY-DEMO-1',created:'2026-09-13',paidDate:o.payment==='Captured'?'2026-09-13':null,paymentRef:'pay_demo_'+o.id.slice(3),attempts:[{id:'ATT-'+o.id.slice(3),provider:'order_demo_'+o.id.slice(3),outcome:o.payment}],changes:[],refunds:n===3?[{id:'RF-1004-1',item:'LI-1',qty:1,amount:200000,status:'Completed',reason:'Sample partial adjustment',approved:200000},{id:'RF-1004-2',item:'LI-1',qty:1,amount:100000,status:'Unknown',reason:'Provider response lost',approved:100000}]:[],documents:[],costs:{production:640000,packaging:80000,shipping:n===3?null:70000,fees:42000,remedy:n===3?null:0},costBasis:'Estimated',bankMatched:false,settlement:o.payment==='Captured'?'Provider settled':'Not settled',dispute:n===3?'Open':'None',cancelled:false,replacement:false,history:[]}));
  for(const o of orders){o.purchase=clone(o.items.map(i=>({title:i.title,frame:i.frame,qty:i.qty,price:i.price})));o.items.forEach(i=>{if(i.parcel)Object.assign(i.parcel,{id:parcelId(o,i),awb:'AWB-DEMO-'+o.id.slice(3)+'-'+i.id.slice(3),shiprocketOrder:'sr_order_demo_'+o.id.slice(3)+'-'+i.id.slice(3),shiprocketShipment:'sr_shipment_demo_'+o.id.slice(3)+'-'+i.id.slice(3)});});}
  orders[5].items[0].quality='Failed';orders[5].items[0].inspections.push({result:'Failed',reason:'Mark on upper frame corner',actor:'Asha',at:'2026-09-13T05:30:00Z',evidence:'Sample inspection photo'});
  const customers=['Meera Shah','Arjun Rao','Nisha Jain','Kabir Das','Nisha Kapoor','Leela Menon'].map((name,n)=>({id:'C-'+(1001+n),name,email:['meera','arjun','nisha','kabir','nisha.k','leela'][n]+'@example.test',phone:n===2||n===4?'Shared sample phone 03':'Sample phone 0'+(n+1),notes:'',verified:false,linked:[],preferences:{email:'Unknown',whatsapp:'Unknown',sms:'Unknown'},consent:[],privacy:n===2?{id:'PR-1003',type:'Correction and promotional opt-out',status:'Awaiting identity check',owner:'Rahul',retention:'Original purchases retained for the sample active-order requirement.'}:null}));
  const cases=[{id:'CS-1004',order:'AS-1004',customer:'C-1004',subject:'Frame damaged in transit',source:'Email · manually captured',owner:'Rahul',priority:'High',status:'Open',verified:false,notes:[],replies:[],due:'2026-09-13',type:'Damage',claim:{evidence:['Sample customer photo','Sample pre-dispatch photo'],decision:'Awaiting review',compensation:'Not submitted',recovered:null,returnStatus:'Not requested',inspection:'Not inspected'}},{id:'CS-1002',order:'AS-1002',customer:'C-1002',subject:'Did my payment go through?',source:'Phone · manually captured',owner:'Rahul',priority:'Normal',status:'Open',verified:false,notes:[],replies:[],due:'2026-09-13',type:'Enquiry'}];
  const messages=[];for(const o of orders.filter(x=>x.payment==='Captured')){messages.push({id:'MSG-'+o.id+'-confirmed',order:o.id,item:'all',kind:'Order confirmation',status:'Provider accepted',attempts:1,template:'confirmation-v1',recipient:customers.find(c=>c.id===o.customer).email});for(const i of o.items){for(const [stage,kind,key] of [[3,'Production started','production'],[8,'Dispatched','dispatch'],[10,'Delivered','delivery']])if(i.stage>=stage)messages.push({id:'MSG-'+o.id+'-'+i.id+'-'+key,order:o.id,item:i.id,kind,status:kind==='Dispatched'&&o.id==='AS-1003'?'Failed':'Provider accepted',attempts:kind==='Dispatched'&&o.id==='AS-1003'?3:1,template:key+'-v1',recipient:customers.find(c=>c.id===o.customer).email});}}
  return {schema:1,revision:0,role:'owner',signedIn:true,revoked:[],scenario:0,orders,customers,cases,messages,products:clone(window.AdminCatalogue),materials:[{id:'MAT-BLACK',name:'Black A2 frame',frame:'black',unit:'pieces',stock:8,incoming:6,supplier:'Framing partner',lead:'5 sample working days',confirmed:'2026-09-12',supplierOwned:false,history:[]},{id:'MAT-WHITE',name:'White A2 frame',frame:'white',unit:'pieces',stock:9,incoming:0,supplier:'Framing partner',lead:'5 sample working days',confirmed:'2026-09-12',supplierOwned:false,history:[]},{id:'MAT-GOLD',name:'Antique Gold A2 frame',frame:'antique-gold',unit:'pieces',stock:6,incoming:4,supplier:'Framing partner',lead:'7 sample working days',confirmed:'2026-09-12',supplierOwned:false,history:[]},{id:'MAT-PACK',name:'A2 packing kit',frame:'packing',unit:'kits',stock:20,incoming:10,supplier:'Packing partner',lead:'3 sample working days',confirmed:'2026-09-12',supplierOwned:false,history:[]}],tasks:[{id:'TASK-PAY',title:'Payment needs checking',record:'AS-1002',owner:'Khalid',due:'2026-09-13',severity:'High',status:'Open',to:'orders/payment?id=AS-1002',next:'Check payment'},{id:'TASK-DAMAGE',title:'Frame damage reported',record:'CS-1004',owner:'Rahul',due:'2026-09-13',severity:'High',status:'Open',to:'support/claim?id=CS-1004',next:'Review evidence'},{id:'TASK-QUALITY',title:'Inspection needs rework',record:'AS-1006',owner:'Asha',due:'2026-09-12',severity:'High',status:'Open',to:'orders/quality?id=AS-1006',next:'Open inspection'}],filters:{q:'',status:'All',owner:'All'},views:[],bulkResults:[],importRows:[],audit:[],paused:false,incident:{owner:'Khalid',status:'Open',note:'Email retry limit reached; review the recorded outcome.'},rules:{version:1,status:'Draft',capacity:6,workingDays:'Monday–Friday',holdMinutes:20,approval:'Demo values only — owner inputs needed',history:[]},connections:{Razorpay:'Simulation only',Shiprocket:'Simulation only',Email:'Sender/provider input needed'},recovery:{status:'Not rehearsed',elapsed:'Not measured',loss:'Not measured'},savedReplies:[{id:'REPLY-1',title:'Delivery update',body:'Thank you for checking in. We are reviewing the latest courier update and will share the confirmed next step.',version:1,status:'Approved sample'},{id:'REPLY-2',title:'Damage evidence',body:'I am sorry your artwork arrived with damage. Please share clear photos of the affected area and packaging so we can review the next step. We can review photographs even if you do not have an unboxing video.',version:1,status:'Approved sample'}]};
 }
 function parcelId(o,i){return 'PAR-'+o.id.slice(3)+'-'+i.id.slice(3);}
 let storageError='',state;try{const data=JSON.parse(localStorage.getItem(KEY));state=data?.schema===1&&Array.isArray(data.orders)&&Array.isArray(data.audit)?data:fresh();}catch{state=fresh();storageError='Saved demo data could not be read. A fresh in-memory demo is open.';}
 let persistedRevision=state.revision;
 function save(replace=false){if(!replace)checkFresh();state.revision++;try{localStorage.setItem(KEY,JSON.stringify(state));persistedRevision=state.revision;storageError='';}catch{storageError='Browser storage is unavailable. Changes work for this visit; refreshing may lose them.';}}
 function checkFresh(){try{const other=JSON.parse(localStorage.getItem(KEY));if(other&&other.revision!==persistedRevision)throw Error('This demo changed in another tab. Reload the latest records before saving.');}catch(e){if(e.message.includes('another tab'))throw e;}}
 function log(entity,action,before,after,reason='Sample workflow'){state.audit.unshift({id:'EV-'+(state.audit.length+1),at:now(),actor:names[state.role],source:'Local prototype',entity,action,before:clone(before??null),after:clone(after??null),reason});}
 function restore(target,saved){for(const k of Object.keys(target))if(!Object.hasOwn(saved,k))delete target[k];for(const [k,v] of Object.entries(saved)){if(v&&typeof v==='object'&&target[k]&&typeof target[k]==='object'&&Array.isArray(v)===Array.isArray(target[k]))restore(target[k],v);else target[k]=clone(v);}if(Array.isArray(target))target.length=saved.length;}
 function expectedBank(o){return o.payment!=='Captured'||o.replacement||o.costs.fees==null?null:o.total-o.refunds.filter(r=>r.status==='Completed').reduce((s,r)=>s+r.amount,0)-o.costs.fees;}
 function mutate(entity,action,fn,reason){checkFresh();if(!state.signedIn||state.revoked.includes(state.role))throw Error('This demo session has ended. Use the sign-in preview or owner recovery.');const before=clone(state);try{fn();for(const o of state.orders){const previous=before.orders.find(x=>x.id===o.id);for(const i of o.items){const prior=previous?.items.find(x=>x.id===i.id);if(prior&&prior.stage!==i.stage){i.stageEvents=i.stageEvents||[];i.stageEvents.push({stage:i.stage,at:now(),source:'Local demo action'});}}if(previous?.bankMatched&&o.bankMatched&&expectedBank(previous)!==expectedBank(o)){o.bankMatched=false;task(o,'Settlement basis changed — review bank match','orders/settlement?id='+o.id);}}log(entity,action,brief(before,entity),brief(state,entity),reason);save();}catch(e){restore(state,before);throw e;}}
 function brief(s,id){const o=s.orders.find(x=>x.id===id);if(o)return {payment:o.payment,items:o.items.map(i=>({id:i.id,stage:stages[i.stage],quality:i.quality,file:i.file})),hold:o.hold,cancelled:o.cancelled,refunds:o.refunds,version:o.version,address:o.address,due:o.due};for(const key of ['customers','products','cases','materials','messages','tasks']){const record=s[key].find(x=>x.id===id);if(record){const snapshot=clone(record);delete snapshot.history;return snapshot;}}const grouped={RULES:'rules',CONNECTIONS:'connections',INCIDENT:'incident',RECOVERY:'recovery',VIEWS:'views',IMPORT:'importRows',BULK:'bulkResults',INTAKE:'intake',WAITLIST:'waitlist'};if(grouped[id])return clone(s[grouped[id]]??null);if(id==='AUTOMATION')return {paused:s.paused,pending:s.messages.filter(m=>m.status==='Queued').length};if(id==='ACCESS')return {role:s.role,signedIn:s.signedIn,revoked:s.revoked};return {revision:s.revision};}
 function order(id){const x=state.orders.find(o=>o.id===id);if(!x)throw Error('Order not found. Return to All orders.');return x;}
 function item(o,id){const x=o.items.find(i=>i.id===id)||(!id?o.items[0]:null);if(!x)throw Error('Item not found in this order.');return x;}
 function guard(permission){const perms={owner:['work','support','finance','catalogue','settings','export'],operations:['work','catalogue'],support:['support']};if(!state.signedIn||state.revoked.includes(state.role)||!perms[state.role]?.includes(permission))throw Error('This preview role does not have '+permission+' access.');}
 function available(m){const reserved=state.orders.filter(o=>!o.cancelled).reduce((s,o)=>s+o.items.filter(i=>i.reserved&&!i.consumed&&(i.frame===m.frame||m.frame==='packing')).reduce((a,i)=>a+i.qty,0),0);return {reserved,free:m.supplierOwned?0:m.stock-reserved};}
 function message(o,i,kind){const id='MSG-'+o.id+'-'+(i?.id||'all')+'-'+kind;if(state.messages.some(m=>m.id===id||m.order===o.id&&m.item===(i?.id||'all')&&m.kind===kind))return;state.messages.push({id,order:o.id,item:i?.id||'all',kind,status:state.paused?'Queued':'Provider accepted',attempts:state.paused?0:1,template:kind.toLowerCase().replaceAll(' ','-')+'-v1',recipient:state.customers.find(c=>c.id===o.customer).email});}
 function task(o,title,to){if(!state.tasks.some(t=>t.record===o.id&&t.title===title&&t.status!=='Resolved'))state.tasks.push({id:'TASK-'+(state.tasks.length+1)+'-'+o.id,title,record:o.id,owner:o.owner,due:'2026-09-13',severity:'High',status:'Open',to,next:'Review next action'});}
 function syncCaseTask(c){const to='support/case?id='+c.id,related=state.tasks.filter(t=>t.record===c.id||t.to===to);if(c.status==='Resolved'){related.forEach(t=>t.status='Resolved');return;}let t=related.find(t=>t.status!=='Resolved');if(!t){t={id:'TASK-CASE-'+c.id+'-'+(state.tasks.length+1),record:c.id,to,status:'Open'};state.tasks.push(t);}Object.assign(t,{title:(c.status==='Reopened'?'Reopened request: ':'Customer request: ')+c.subject,owner:c.owner,due:c.due,severity:c.priority,next:'Review request'});}
 function resolveTask(record,match){state.tasks.filter(t=>t.record===record&&(!match||t.title.includes(match))).forEach(t=>t.status='Resolved');}
 function verifyPayment(id,outcome){guard('finance');mutate(id,'Verify existing payment',()=>{const o=order(id);o.attempts[0].outcome=outcome;if(o.payment==='Captured'){o.attempts.push({id:'CHECK-'+(o.attempts.length+1),provider:o.paymentRef,outcome:'Duplicate verified; no new effect'});return;}if(outcome!=='Captured'){o.payment=outcome;task(o,'Payment needs checking','orders/payment?id='+id);return;}o.payment='Captured';o.paidDate='2026-09-13';o.items.forEach(i=>i.stage=Math.max(i.stage,1));o.version++;message(o,null,'Order confirmation');resolveTask(id,'Payment');if(o.cancelled||o.items.some(i=>available(state.materials.find(m=>m.frame===i.frame)).free<i.qty))task(o,'Paid order needs readiness review','orders/job?id='+id);});}
 function progress(id,itemId,operation,data={}){guard('work');mutate(id,operation,()=>{const o=order(id),i=item(o,itemId);if(o.cancelled||o.hold)throw Error('Resolve the current hold or cancellation before moving this job.');if(o.payment!=='Captured')throw Error('Only verified captured payment releases production.');const product=state.products.find(p=>p.id===i.artId);
   if(operation==='reserve'){if(i.stage!==1)throw Error('This item has already been released or is not ready.');if(!product?.fileApproved||!product.sample)throw Error('An approved production file and physical sample are required.');const daily=state.orders.reduce((a,o)=>a+o.items.filter(x=>x.stage>=2&&x.stage<5).reduce((n,x)=>n+x.qty,0),0);if(daily+i.qty>Number(state.rules.capacity))throw Error('Sample daily capacity is full. Keep the original promise and assign a readiness task.');const mats=state.materials.filter(m=>m.frame===i.frame||m.frame==='packing');if(mats.some(m=>available(m).free<i.qty))throw Error('Materials are unavailable. A paid order stays visible; another order’s reservation is retained.');i.reserved=true;i.file=product.fileVersion;i.privateFileId=product.printFileId||null;i.stage=2;}
   else if(operation==='start'){if(i.stage!==2||!i.reserved)throw Error('Reserve and release the job before starting.');const materials=state.materials.filter(m=>m.frame===i.frame||m.frame==='packing');if(materials.some(m=>m.supplierOwned||available(m).free<0||m.stock<i.qty))throw Error('Reserved materials need review after a stock change. Restore verified availability before printing.');i.stage=3;i.started=now();i.consumed=true;state.materials.filter(m=>m.frame===i.frame||m.frame==='packing').forEach(m=>{m.stock-=i.qty;m.history.unshift({at:now(),kind:'Consumed',qty:-i.qty,reason:o.id+' / '+i.id});});message(o,i,'Production started');}
   else if(operation==='printed'){if(i.stage!==3)throw Error('Printing must be in progress.');i.stage=4;}
   else if(operation==='inspection'){if(i.stage!==4)throw Error('Complete printing and framing before inspection.');if(!data.evidence)throw Error('Add inspection evidence before recording a result.');const passed=Boolean(data.passed);if(passed&&i.quality==='Failed')throw Error('Record the rework correction before a new passing inspection.');if(!passed&&!data.reason?.trim())throw Error('Describe the failed check so the studio can correct it.');i.inspections.push({result:passed?'Passed':'Failed',actor:names[state.role],at:now(),reason:data.reason||'All five checks passed',evidence:data.evidence});i.quality=passed?'Passed':'Failed';if(passed){i.stage=5;resolveTask(id,'Inspection');}else task(o,'Inspection needs rework','orders/quality?id='+id+'&item='+i.id);}
   else if(operation==='rework'){if(i.quality!=='Failed')throw Error('This job has no failed inspection to rework.');if(!data.reason?.trim())throw Error('Record what was corrected.');i.quality='Awaiting recheck';i.rework=data.reason;}
   else if(operation==='pack'){if(i.stage!==5||i.quality!=='Passed')throw Error('A passed inspection is required before packing.');for(const k of ['weight','length','width','height'])if(!Number.isFinite(Number(data[k]))||Number(data[k])<=0||Number(data[k])>200)throw Error('Enter a valid positive '+k+' (maximum 200 for this A2 sample).');if(!data.checks||!data.photo||!data.version)throw Error('Complete every packing check, evidence and packaging version.');i.packing=clone(data);i.stage=6;}
   else throw Error('Unknown production action.');o.version++;
  });}
 function shipment(id,itemId,operation,data={}){guard('work');mutate(id,operation,()=>{const o=order(id),i=item(o,itemId);if(operation==='book'){if(o.hold||o.cancelled)throw Error('Resolve the order hold before booking.');if(i.stage!==6||!i.packing)throw Error('Pack and measure this item before booking.');if(i.parcel)throw Error('A booking already exists or is uncertain. Verify it before creating another.');if(!data.serviceable)throw Error('Confirm serviceability and the sample rate first.');i.parcel={id:parcelId(o,i),status:data.outcome==='Unknown'?'Booking unknown':'Pickup booked',awb:'',shiprocketOrder:'',shiprocketShipment:'',history:[],protection:'Unconfirmed',rate:70000};if(data.outcome==='Unknown'){task(o,'Booking outcome unknown','orders/parcel?id='+id+'&item='+i.id);}else {setRefs(o,i);i.stage=7;}}
   else {if(!i.parcel)throw Error('No shipment exists for this item.');const parcel=i.parcel;if(operation==='reconcile'){if(parcel.status!=='Booking unknown')throw Error('There is no uncertain booking to recover.');setRefs(o,i);i.stage=7;parcel.status='Pickup booked';resolveTask(id,'Booking');}
    else if(operation==='handover'){if(i.stage!==7)throw Error('Book pickup before handover.');if(o.hold||o.cancelled||parcel.correction)throw Error('Resolve the hold or booked-address follow-up before handover.');if(!data.evidence?.trim())throw Error('Record collection/handover evidence.');i.stage=8;parcel.status='Shipped';parcel.handover=data.evidence;message(o,i,'Dispatched');}
    else if(operation==='tracking'){if(i.stage<8)throw Error('A shipping label is not physical dispatch. Record handover first.');if(i.stage===10&&data.outcome!=='Delivered'){parcel.history.push({at:now(),status:data.outcome,detail:'Older event retained; delivered state unchanged'});return;}if(data.outcome==='Delivered'){i.stage=10;parcel.status='Delivered';message(o,i,'Delivered');resolveTask(id,'Delivery');}else if(data.outcome==='Out for delivery'){i.stage=9;parcel.status=data.outcome;}else if(['Delivery failed','Returning to studio','Tracking stale','Pickup failed'].includes(data.outcome)){parcel.status=data.outcome;task(o,'Delivery exception — '+data.outcome,'orders/parcel?id='+id+'&item='+i.id);}else throw Error('Choose a supported tracking outcome.');}
    else if(operation==='reattempt'){if(!['Delivery failed','Tracking stale','Pickup failed'].includes(parcel.status))throw Error('A failed or stale delivery needs review before a reattempt.');if(!data.evidence?.trim())throw Error('Record customer contact and the reattempt reference.');parcel.reattempt=data.evidence;parcel.status='Reattempt requested';}
    else if(operation==='fallback'){if(!data.evidence?.trim())throw Error('Record the provider dashboard action and reference.');parcel.fallback=data.evidence;if(parcel.correction)parcel.correction=false;}
    else throw Error('Unknown parcel action.');}
   i.parcel.history.push({at:now(),status:i.parcel.status,detail:data.evidence||'Simulated provider result'});o.version++;
  });}
 function setRefs(o,i){Object.assign(i.parcel,{awb:'AWB-DEMO-'+o.id.slice(3)+'-'+i.id.slice(3),shiprocketOrder:'sr_order_demo_'+o.id.slice(3)+'-'+i.id.slice(3),shiprocketShipment:'sr_shipment_demo_'+o.id.slice(3)+'-'+i.id.slice(3)});}
 const refundReserved=r=>['Approved','Submitted','Unknown','Completed'].includes(r.status);
 const refundable=o=>o.total-o.refunds.filter(refundReserved).reduce((s,r)=>s+r.amount,0);
 function refund(id,operation,data={}){guard('finance');mutate(id,'Refund: '+operation,()=>{const o=order(id);if(o.payment!=='Captured')throw Error('A captured payment is required.');if(operation==='request'){const i=item(o,data.item),amount=Number(data.amount),qty=Number(data.qty);if(!Number.isSafeInteger(amount)||amount<=0||amount>i.price*qty||amount>refundable(o))throw Error('Amount must be within the item value and current uncommitted balance.');if(!Number.isInteger(qty)||qty<1||qty>i.qty)throw Error('Select an eligible item quantity.');if(!data.reason?.trim())throw Error('A remedy reason is required.');o.refunds.push({id:'RF-'+o.id.slice(3)+'-'+(o.refunds.length+1),item:i.id,qty,amount,status:'Requested',reason:data.reason,approved:null});}
   else {const r=o.refunds.find(r=>r.id===data.ref);if(!r)throw Error('Refund not found.');if(operation==='edit'){if(!['Requested','Approved'].includes(r.status))throw Error('Submitted refunds cannot be edited.');const amount=Number(data.amount);if(!Number.isSafeInteger(amount)||amount<=0||amount>item(o,r.item).price*r.qty)throw Error('Enter a valid item-scoped amount.');r.amount=amount;r.status='Requested';r.approved=null;}
    else if(operation==='approve'){if(r.status!=='Requested')throw Error('Only a requested refund can be approved.');if(o.dispute==='Open'&&!data.overlap)throw Error('Review the open dispute and existing remedy before approving more compensation.');if(r.amount>refundable(o))throw Error('Another refund has reserved this balance. Reload and reduce the amount.');const scoped=o.refunds.filter(x=>x.id!==r.id&&x.item===r.item&&refundReserved(x)).reduce((s,x)=>s+x.amount,0);if(scoped+r.amount>item(o,r.item).price*item(o,r.item).qty)throw Error('Other remedies already use this item’s refundable value.');r.status='Approved';r.approved=r.amount;}
    else if(operation==='submit'){if(r.status!=='Approved'||r.approved!==r.amount)throw Error('Approve the current amount before submission.');r.status=data.outcome==='Unknown'?'Unknown':'Submitted';r.provider='rfnd_demo_'+r.id;}
    else if(operation==='verify'){if(!['Unknown','Submitted'].includes(r.status))throw Error('Only a submitted or uncertain refund can be verified.');if(!['Completed','Failed','Unknown'].includes(data.outcome))throw Error('Choose a verified result.');r.status=data.outcome;if(r.status==='Completed')message(o,item(o,r.item),'Refund confirmed '+r.id);}
    else throw Error('Unknown refund action.');}o.version++;
  });}
 function change(id,data){guard('support');mutate(id,'Order change: '+data.type,()=>{const o=order(id);if(Number(data.version)!==o.version)throw Error('This order changed since the request was opened. Reload and review the current production/hold state.');if(!data.identity)throw Error('Verify identity before changing purchased fulfilment details.');if(!data.reason?.trim())throw Error('Record the request and decision reason.');const before={address:o.address,due:o.due,hold:o.hold,cancelled:o.cancelled};
   if(data.type==='Hold')o.hold=true;
   else if(data.type==='Release hold'){if(o.cancelled)throw Error('A cancelled order cannot be released.');o.hold=false;}
   else if(data.type==='Cancel eligible items'){if(o.items.some(i=>i.stage>=3))throw Error('Printing has started. This cancellation needs owner policy review; do not treat consumed materials as unused.');o.cancelled=true;o.hold=true;o.items.forEach(i=>i.reserved=false);task(o,'Cancellation remedy review','orders/refund?id='+id);}
   else if(data.type==='Correct address'){if(!data.value?.trim()||!data.serviceable)throw Error('Enter the corrected address and confirm serviceability.');o.address=data.value;o.items.filter(i=>i.parcel).forEach(i=>{i.parcel.correction=true;task(o,'Booked shipment needs address follow-up','orders/parcel?id='+id+'&item='+i.id);});}
   else if(data.type==='Revise promise'){if(!/^\d{4}-\d{2}-\d{2}$/.test(data.value))throw Error('Enter the revised promise as YYYY-MM-DD.');o.due=data.value;}
   else if(data.type==='Frame / price change'){task(o,'Owner review: supported cancel/reorder','orders/change?id='+id);}
   else throw Error('Unknown change request.');o.changes.push({at:now(),type:data.type,reason:data.reason,before,after:{address:o.address,due:o.due,hold:o.hold,cancelled:o.cancelled}});o.version++;
  },data.reason);}
 function reset(story=0){state=fresh();state.scenario=story;if(story===4||story===18){state.materials[0].stock=1;state.orders[0].payment='Captured';state.orders[0].items[0].stage=1;state.orders[0].paidDate='2026-09-13';}if(story===8){const o=state.orders[0],i=o.items[0];o.payment='Captured';i.stage=6;i.quality='Passed';i.packing={weight:4.2,length:72,width:54,height:9,version:'PACK-DEMO-1',photo:'Sample parcel evidence',checks:true};i.parcel={id:parcelId(o,i),status:'Booking unknown',history:[],protection:'Unconfirmed'};}if(story===10){const o=state.orders[0],i=o.items[0];o.payment='Captured';i.stage=8;i.parcel={id:parcelId(o,i),status:'Delivery failed',history:[],protection:'Unconfirmed'};setRefs(o,i);task(o,'Delivery exception — Delivery failed','orders/parcel?id='+o.id);}if(story===16){const p=state.products[0];p.status='Draft';p.sample=false;p.rights=false;}if(story===20)state.role='operations';try{const old=JSON.parse(localStorage.getItem(KEY));if(old?.revision)state.revision=old.revision;}catch{}save(true);}
 function setRole(role){if(!Object.hasOwn(names,role))return;checkFresh();state.role=role;save();}
 function summary(o){if(o.cancelled)return 'Cancelled';if(o.hold)return 'On hold';const s=o.items.map(i=>i.stage);if(s.every(x=>x===10))return 'Delivered';if(s.some(x=>x===10))return 'Part delivered';return stages[Math.min(...s)];}
 function csv(rows){return rows.map(row=>row.map(v=>{let s=String(v??'');if(/^[\s]*[=+@-]/.test(s))s="'"+s;return '"'+s.replaceAll('"','""')+'"';}).join(',')).join('\r\n');}
 window.AdminStore={get state(){return state;},get storageError(){return storageError;},KEY,stages,names,clone,now,order,item,guard,save,expectedBank,mutate,log,available,verifyPayment,progress,shipment,refund,refundable,change,reset,setRole,summary,message,task,syncCaseTask,resolveTask,csv,parcelId};
})();
