/* Owner-first reporting, connections, staff and isolated guided demonstrations. */
(() => {
 'use strict';
 const A=window.AdminUI,S=A.S,V=window.StudioMedia,U=window.StudioUI,{esc,money,button,actions,pill,panel,notice,field,select,textarea,check,form,details,link,facts,modal}=A;
 const today=window.StudioState.demoDate;
 const refunds=o=>o.refunds.filter(r=>r.status==='Completed').reduce((n,r)=>n+r.amount,0);
 function reportHref(extra={}){return U.query('reports',extra,true);}
 function bounds(){let range=A.params.get('range')||'all',from=A.params.get('from')||'',to=A.params.get('to')||today;if(range==='today')from=to=today;if(range==='week'){const d=new Date(today+'T00:00:00Z');d.setUTCDate(d.getUTCDate()-6);from=d.toISOString().slice(0,10);to=today;}if(range==='month'){from=today.slice(0,7)+'-01';to=today;}if(range==='all'){from='';to='';}return {range,from,to};}
 function metric(label,value,sub,filter){return `<a class="stat" href="#${esc(reportHref({metric:filter}))}"><span class="label">${esc(label)}</span><strong>${esc(value)}</strong><small>${esc(sub)}</small></a>`;}
 function reportsMain(){const view=A.params.get('view')||'sales',r=bounds(),inRange=date=>date&&(!r.from||date>=r.from)&&(!r.to||date<=r.to),orders=S.state.orders.filter(o=>!o.replacement&&inRange(view==='operations'?o.created:o.paidDate)),captured=orders.filter(o=>o.payment==='Captured'),allOps=S.state.orders.filter(o=>inRange(o.created)),nonCancelled=allOps.filter(o=>!o.cancelled&&!o.replacement),paid=captured.reduce((n,o)=>n+o.total,0),back=captured.reduce((n,o)=>n+refunds(o),0),matched=captured.filter(o=>o.bankMatched&&S.expectedBank(o)!==null),metricFilter=A.params.get('metric');let body='';
  const tabs=`<nav class="inline-tabs" aria-label="Report type">${[['sales','Sales & money'],['products','Products'],['operations','Operations']].map(([id,t])=>`<a href="#${esc(reportHref({view:id,metric:null,detail:null}))}"${view===id?' aria-current="page"':''}>${t}</a>`).join('')}</nav>`;
  const filter=`<form class="filter-form" data-filter="reports"><input type="hidden" name="view" value="${esc(view)}">${select('range','Date range',[['all','All demo dates'],['today','Demo day'],['week','Last 7 demo days'],['month','Demo month'],['custom','Custom']],r.range)}${field('from','From',r.from,'date','Choose Custom to use these dates.',false)}${field('to','To',r.to,'date','',false)}<button type="submit" class="button secondary">Apply</button></form><p class="small">${view==='operations'?'Order-created cohort. Later fulfilment and linked support states are shown.':'Payment-date cohort. Later refunds and bank matches for these purchases are included; this is not a cash-events report.'} Demo reference date: 13 September 2026.</p>`;
  if(r.from&&r.to&&r.from>r.to)return A.heading('Reports','The numbers behind the work.',tabs+filter+notice('Check the dates','The start date must not be after the end date.','warn'));
  if(view==='sales'){
   let rows=captured;if(metricFilter==='refunds')rows=rows.filter(o=>refunds(o)>0);if(metricFilter==='matched')rows=matched;
   const unknown=rows.filter(o=>Object.values(o.costs).some(v=>v===null||v===undefined));
   body=`<div class="stats">${metric('Paid purchases',String(captured.length),'Excludes replacement orders','paid')}${metric('Collected',money(paid),'Captured payments for this cohort','collected')}${metric('Confirmed refunds',money(back),'Completed outcomes only','refunds')}${metric('Bank matched',money(matched.reduce((n,o)=>n+S.expectedBank(o),0)),matched.length+' matched purchases','matched')}</div>`+(metricFilter?`<div class="section-line"><p class="small">Filtered: ${esc(metricFilter)}</p>${link(reportHref({metric:null}),'Show all purchases','text-link')}</div>`:'')+U.dataTable('Money by purchase',['Order','Collected','Refunded','Expected bank','Bank match','Review'],rows.map(o=>({id:o.id,cells:[link('orders?id='+o.id,o.id),money(o.total),money(refunds(o)),money(S.expectedBank(o)),pill(o.bankMatched?'Matched':'Not matched',o.bankMatched?'':'warn'),link(reportHref({detail:'settlement',id:o.id}),'Money record')]})))+details('Costs, disputes & unresolved amounts',`<p class="small">${unknown.length} of ${rows.length} displayed purchases have unknown costs. Estimates are labelled. Recorded contribution is not net business profit.</p>`+U.dataTable('Costs and financial exceptions',['Order','Cost basis','Recorded costs','Recorded contribution','Dispute','Action'],rows.map(o=>{const known=Object.values(o.costs).every(v=>v!==null&&v!==undefined),cost=known?Object.values(o.costs).reduce((a,b)=>a+b,0):null;return {cells:[link('orders?id='+o.id,o.id),esc(o.costBasis),money(cost),known?money(o.total-refunds(o)-cost):'Unknown',esc(o.dispute),actions(button('costs','Edit costs',{id:o.id},'button secondary small-button'),link(reportHref({detail:'dispute',id:o.id}),'Dispute'))]};})))+actions(link(reportHref({detail:'settlements'}),'All settlements','button secondary'),button('export','Export money records',{kind:'finance'},'button secondary'));
  }else if(view==='products'){
   const groups=new Map();for(const o of captured)for(const i of o.items){const k=i.artId+'|'+i.frame,x=groups.get(k)||{product:i.artId,title:i.title,frame:i.frame,qty:0,total:0,refund:0,orders:new Set()};x.qty+=i.qty;x.total+=i.qty*i.price;x.refund+=o.refunds.filter(f=>f.status==='Completed'&&f.item===i.id).reduce((n,f)=>n+f.amount,0);x.orders.add(o.id);groups.set(k,x);}const rows=[...groups.values()].sort((a,b)=>b.total-a.total),max=Math.max(1,...rows.map(x=>x.total));body=U.dataTable('Artwork sales',['Artwork / finish','Units','Recorded sales','Confirmed refunds','Original orders'],rows.map(x=>({cells:[link('products?id='+x.product,x.title)+`<small>${esc(x.frame)}</small>`,String(x.qty),money(x.total)+`<span class="trend-bar" style="width:${Math.round(x.total/max*100)}%" aria-hidden="true"></span>`,money(x.refund),[...x.orders].map(id=>link('orders?id='+id,id)).join(' / ')]})))+details('By collection',(()=>{const sums=new Map();for(const x of rows){const k=S.state.products.find(p=>p.id===x.product)?.collection||'Unknown collection',s=sums.get(k)||{qty:0,total:0};s.qty+=x.qty;s.total+=x.total;sums.set(k,s);}return A.table('Collection results',['Collection','Units','Recorded sales'],[...sums].map(([k,s])=>[esc(k),s.qty,money(s.total)]));})())+`<p class="small">Historic item prices are used, not today's catalogue prices. Replacement orders are excluded.</p>`;
  }else{
   const late=nonCancelled.filter(o=>o.originalDue<today&&o.items.some(i=>i.stage<10)),delivered=nonCancelled.flatMap(o=>o.items).filter(i=>i.stage===10),cohortCases=S.state.cases.filter(c=>allOps.some(o=>o.id===c.order)),open=cohortCases.filter(c=>c.status!=='Resolved'),damage=cohortCases.filter(c=>c.claim);let rows=nonCancelled;if(metricFilter==='late')rows=late;if(metricFilter==='delivered')rows=rows.filter(o=>o.items.some(i=>i.stage===10));if(metricFilter==='cases')rows=rows.filter(o=>open.some(c=>c.order===o.id));if(metricFilter==='damage')rows=rows.filter(o=>damage.some(c=>c.order===o.id));body=`<div class="stats">${metric('Late open purchases',String(late.length),'Original promise is the baseline','late')}${metric('Delivered items',String(delivered.reduce((n,i)=>n+i.qty,0)),'Not the same as fully delivered orders','delivered')}${metric('Open support cases',String(open.length),'Cases linked to the selected cohort','cases')}${metric('Return / damage cases',String(damage.length),'Reviewed individually; not a defect rate','damage')}</div>`+U.dataTable('Operational work',['Order','Original promise','Current promise','Progress','Attention'],rows.map(o=>({cells:[link('orders?id='+o.id,o.id),esc(o.originalDue),esc(o.due),pill(S.summary(o),'neutral'),esc(U.issue(o).text)]})))+details('Customer care & service detail',facts([['First response recorded',cohortCases.filter(c=>c.firstResponseAt).length+' / '+cohortCases.length+' linked cases'],['Return-to-origin parcels',String(nonCancelled.flatMap(o=>o.items).filter(i=>i.parcel?.status==='Returning to studio').length)],['Failed / unknown messages',String(S.state.messages.filter(m=>allOps.some(o=>o.id===m.order)&&['Failed','Unknown'].includes(m.status)).length)]])+actions(link('support/messages','Review recorded messages','button secondary'),link('connections','Review connections','button secondary')))+actions(button('weekly-digest','Preview weekly summary',{},'button secondary'));
  }
  const detail=A.params.get('detail');if(detail){const original=detail==='dispute'?'orders/dispute':detail==='settlements'?'orders/settlements':'orders/settlement';body+=`<section class="record-workspace"><header class="record-top"><h2>${esc(detail==='dispute'?'Dispute review':detail==='settlements'?'Settlement register':'Purchase money record')}</h2>${link(reportHref({detail:null,id:null}),'Close details','text-link')}</header><div class="editor-body">${U.embed(original,{id:A.params.get('id')||captured[0]?.id||S.state.orders[0]?.id})}</div></section>`;}
  return A.heading('Reports','See the result. Open the records behind it.',tabs+filter+body);
 }
 A.screens.reports=reportsMain;
 const presets={operations:{label:'Operations',description:'Orders, production, parcels, catalogue and materials. No refunds, finance, owner settings or exports.',permissions:['orders','production','shipping','catalogue','materials']},support:{label:'Customer support',description:'Customer records, support, notes and remedy recommendations. No provider refunds or private print files.',permissions:['customers','support','communications']}};
 A.screens.staff=()=>A.heading('Staff & Access','You are the owner. Add colleagues only when you need them.',panel('People',U.dataTable('Staff directory',['Person','Access','Status',''],[{cells:['<strong>You</strong><small>Owner</small>','All areas, approvals and financial actions',pill('Active owner'),'<span class="small">Owner access retained</span>']},...S.state.staff.map(p=>({cells:[`<strong>${esc(p.name)}</strong><small>${esc(p.email)}</small>`,esc(presets[p.preset]?.label||p.preset),pill(p.active?'Demo staff record':'Disabled in demo',p.active?'neutral':'warn'),button('staff-toggle',p.active?'Disable access':'Enable access',{id:p.id},'button secondary small-button')]}))]))+notice('Staff records are local previews','Adding a person does not send an invitation or create a real account. Real login and server-enforced permissions remain outside this prototype.')+details('Permission presets',Object.values(presets).map(p=>`<h3>${esc(p.label)}</h3><p>${esc(p.description)}</p>`).join(''))+panel('Private files & backup',window.StudioCMS.vaultBar()+`<p class="small">Download a backup after important uploads. Private file contents stay encrypted in it; public images, metadata and fictional admin records do not. Keep backups outside your public website folder.</p>`+actions(button('backup-export','Download full local backup'),button('backup-restore','Restore a backup',{},'button secondary'),button('storage-persist','Request persistent local storage',{},'button secondary')))+details('Session, history & recovery',actions(button('session-signout','End demo session',{},'button secondary'),button('owner-recover','Owner recovery preview',{},'button secondary'),link('settings/activity','Activity history','button secondary'),link('settings/recovery','Recovery rehearsal','button secondary'))+`<p class="small">The local vault locks on sign-out, page close and after 15 minutes without private-file activity. It is not a substitute for an authenticated production admin.</p>`),actions(button('staff-add','Add staff')));
 A.handlers['staff-add']=()=>{S.guard('settings');modal('Add a staff record','Create a local access preview. No invitation is sent, and no real account is provisioned.',field('name','Full name')+field('email','Email address','','email')+select('preset','Permission preset',Object.entries(presets).map(([k,p])=>[k,p.label]))+check('understand','This is a local staff preview, not a live invitation'),d=>{if(!d.understand)throw Error('Confirm that this is a local preview.');if(!presets[d.preset])throw Error('Choose a supported permission preset.');if(S.state.staff.some(x=>x.email.toLowerCase()===d.email.toLowerCase()))throw Error('A staff record with this email already exists.');S.mutate('ACCESS','Create local staff record',()=>S.state.staff.push({id:'STAFF-'+Date.now().toString(36),name:d.name.trim(),email:d.email.trim(),preset:d.preset,permissions:presets[d.preset].permissions,active:true,created:S.now()}));},'Add local staff record');};
 A.handlers['staff-toggle']=({id})=>{S.guard('settings');const person=S.state.staff.find(p=>p.id===id);if(!person)throw Error('Staff record not found.');modal(person.active?'Disable this staff record?':'Enable this staff record?','This changes only the local permission preview. The owner cannot be removed.',textarea('reason','Reason'),d=>S.mutate(id,'Change local staff access',()=>person.active=!person.active,d.reason),'Confirm change',person.active);};
 A.handlers['backup-export']=async()=>{S.guard('settings');await V.ready;V.download(await V.exportBackup(S.clone(S.state)),'aalishaan-admin-backup-'+new Date().toISOString().slice(0,10)+'.zip');A.toast('Backup downloaded. Keep it and your vault passphrase outside the public repository.');};
 function validateRestore(x){const s=x.state,arrays=['orders','customers','cases','messages','products','materials','tasks','views','bulkResults','importRows','audit','savedReplies','revoked'];for(const k of arrays)if(!Array.isArray(s[k]))throw Error('The backup is missing '+k+'.');if(!s.rules||!s.connections||!s.incident||!s.recovery||s.schema!==1)throw Error('The backup has incomplete operating settings.');if(JSON.stringify(s).length>4*1024*1024)throw Error('This backup has too much local record data for a safe restore.');const unique=(xs,label)=>{if(xs.some(x=>!x||typeof x.id!=='string')||new Set(xs.map(x=>x.id)).size!==xs.length)throw Error('Invalid '+label+' identities in backup.');};for(const k of ['orders','customers','cases','products','materials'])unique(s[k],k);for(const p of s.products){if(typeof p.title!=='string'||typeof p.slug!=='string'||!Array.isArray(p.history)||!p.prices||!Number.isInteger(p.version))throw Error('Invalid product in backup.');for(const k of ['black','white','antique-gold'])if(!Number.isSafeInteger(p.prices[k])||p.prices[k]<0)throw Error('Invalid price in backup.');}for(const o of s.orders){if(!s.customers.some(c=>c.id===o.customer)||!Array.isArray(o.items)||!Array.isArray(o.refunds)||!Array.isArray(o.history)||!o.costs)throw Error('An order has invalid linked records.');for(const i of o.items)if(!Number.isInteger(i.stage)||i.stage<0||i.stage>10||!s.products.some(p=>p.id===i.artId))throw Error('An order has invalid product or journey data.');}if(x.pub.some(f=>!f.id||!Number.isSafeInteger(f.size)||f.size<1)||x.priv.some(f=>!f.id||!Number.isSafeInteger(f.size)||f.size<1))throw Error('Invalid file metadata in backup.');return x;}
 A.handlers['backup-restore']=()=>{S.guard('settings');modal('Restore this browser from a backup?','This replaces current local records and uploaded files, then locks the vault. Download a backup of this browser first. Public website files stay unchanged.',`<label class="field"><span>Admin backup ZIP</span><input type="file" name="file" aria-label="Admin backup ZIP" accept=".zip,application/zip" required></label>`+check('backup','I have downloaded a backup of the current local workspace')+check('replace','Replace this browser workspace with the selected backup'),async d=>{if(!d.backup||!d.replace)throw Error('Confirm both backup and replacement.');const checked=validateRestore(await V.inspectBackup(d.file));const oldState=S.clone(S.state),rollback=validateRestore(await V.inspectBackup(await V.exportBackup(oldState)));const revision=S.state.revision;try{localStorage.setItem('aalishaan-a2-restore-check',JSON.stringify(checked.state));localStorage.removeItem('aalishaan-a2-restore-check');}catch{throw Error('Not enough browser storage to restore safely. No files were changed.');}if(S.state.revision!==revision)throw Error('Records changed while reading the backup. Try again.');try{await V.restoreFiles(checked);S.mutate('BACKUP','Restore local browser backup',()=>{const rev=S.state.revision;Object.keys(S.state).forEach(k=>delete S.state[k]);Object.assign(S.state,S.clone(checked.state),{revision:rev,role:'owner',signedIn:true});window.StudioState.enrichProducts();});if(S.storageError)throw Error(S.storageError);}catch(e){await V.restoreFiles(rollback);Object.keys(S.state).forEach(k=>delete S.state[k]);Object.assign(S.state,oldState);S.save();throw Error('Restore did not complete; rollback attempted. '+e.message);}history.replaceState(null,'','#staff');},'Restore local backup',true);};
 A.handlers['storage-persist']=async()=>{S.guard('settings');A.toast(await V.persist()?'The browser granted persistent-storage permission. External backups are still necessary.':'The browser did not grant persistent storage. Keep originals and regular external backups.');};
 const providers=[['Razorpay','Captured payments, refunds and settlements.','Verify a saved payment or refund reference; never retry an uncertain payment by charging again.'],['Shiprocket','Bookings, pickup references and delivery updates.','Check the original shipment before retrying an uncertain booking. Record physical handover separately.'],['Email','Order confirmation, production, dispatch and delivery updates.','Check the recorded send result before retrying. Manual follow-up does not mean a provider delivered a message.'],['WhatsApp','Optional customer contact channel.','Customer profiles can open a draft in WhatsApp. Integrated sending is not connected.'],['SMS','Optional customer contact channel.','Customer profiles can open a draft in a supported SMS app. Integrated sending is not connected.']];
 A.screens.connections=()=>A.heading('Connections','One place to check the services behind your work.',`<div class="connection-grid">${providers.map(([name,purpose,fallback])=>{const result=S.state.providerChecks?.[name],status=result?.result||'Not configured';return `<section class="connection-card"><div class="connection-brand"><h2>${esc(name)}</h2>${pill(status,status==='Demo test passed'?'neutral':'warn')}</div><p>${esc(purpose)}</p><p class="small">Last local check: ${result?esc(new Date(result.at).toLocaleString('en-IN')):'Not run'}</p>${actions(button('connection','Review connection',{provider:name},'button secondary'))}${details('Setup & fallback',`<p>Live integration is not configured. Do not paste API keys or provider secrets into this browser prototype.</p><p>${esc(fallback)}</p>${result?`<p>Latest note: ${esc(result.note)}</p>`:''}`)}</section>`;}).join('')}</div>`+details('Automation & service health',facts([['Milestone follow-ups',S.state.paused?'Paused in demo':'Running in demo'],['Owned incident',esc(S.state.incident.status)],['Next action',esc(S.state.incident.note)]])+actions(button('automation-pause',S.state.paused?'Review resuming follow-ups':'Pause follow-ups',{},'button secondary'),button('automation-replay','Replay safe queued work',{},'button secondary'),link('support/messages','Messages & outcomes','button secondary'),link('settings/system','Incident & recovery details','button secondary'),link('settings/automation','Automation rules','button secondary')))+`<p class="small">No live accounts are contacted here. A demo test result is not a verified test or live connection.</p>`);
 A.handlers.connection=({provider})=>{S.guard('settings');if(!providers.some(x=>x[0]===provider))throw Error('Unknown provider.');modal(provider+' setup preview','No provider request is made. Record a selected outcome to test the admin workflow; do not enter credentials.',select('result','Demo outcome',['Demo test passed','Needs attention','Not configured'])+textarea('reason','Note / next action'),d=>S.mutate('CONNECTIONS',provider+' local setup check',()=>{S.state.providerChecks=S.state.providerChecks||{};S.state.providerChecks[provider]={result:d.result,note:d.reason,at:S.now()};S.state.connections[provider]=d.result;if(d.result==='Needs attention')S.state.incident={owner:S.names.owner,status:'Open',note:provider+': '+d.reason};}), 'Record demo outcome');};
 const guided=[[2,'01 / A normal order, start to finish'],[3,'02 / Payment needs verification'],[5,'03 / Cancellation before printing'],[7,'04 / Failed inspection and rework'],[8,'05 / Shipment booking is uncertain'],[10,'06 / A delivery problem'],[11,'07 / Damage after delivery'],[16,'08 / Add and review a product']];
 function routeScenario(n){const o=S.state.orders[0],c=S.state.cases[0];if(n===4||n===18)return 'products/material?id=MAT-BLACK';if(n===5||n===6)return 'orders?id='+o.id+'&panel=changes';if(n===7)return 'orders?id='+o.id+'&stage=5';if(n===8)return 'orders?id='+o.id+'&stage=7';if(n===10)return 'orders?id='+o.id+'&stage=9';if(n===11)return 'support?view=returns'+(c?'&id='+c.id:'');if(n===12)return 'support?view=refunds&refund='+o.id;if(n===13)return 'customers?id='+o.customer;if(n===14)return 'support'+(c?'?id='+c.id:'');if(n===15)return 'support/messages';if(n===16)return 'products?id=ART-DEMO&tab=review';if(n===17)return 'products/import';if(n===19)return 'reports';if(n===20)return 'support?view=refunds&refund='+o.id;if(n===21)return 'connections';if(n===22)return 'help?view=coverage';if(n===23)return 'help?view=scope';return 'orders?id='+o.id;}
 A.screens.help=()=>{const view=A.params.get('view')||'demos';let content='';if(view==='coverage')content=notice('Approved design, separate live acceptance','This admin redesign implements the approved prototype plan. Production authentication, shared storage, provider calls and live publication still require integration and verification.')+A.table('Preserved operating capabilities',['Capability','Location','Coverage'],window.AdminWireframeScope.map(([id,title,to,stories])=>[esc(id)+' / '+esc(title),link(to,'Open workspace'),stories.map(n=>button('story','US'+String(n).padStart(2,'0'),{n},'text-button')).join(' ')]))+details('Delivery checks',`<p>Read <a href="TEST-RESULTS.md" target="_blank" rel="noopener">TEST-RESULTS.md</a> for the checks performed on this replacement. Prototype tests do not establish live-provider or production-security readiness.</p>`);else if(view==='scope')content=panel('Kept deliberately out of everyday work',`<p>Accounting, full CRM, marketing campaigns, a helpdesk system and additional marketplaces remain deferred. Existing costs, customers, case handling and exports remain in their seven approved admin sections.</p><p>Public pages and the approved catalogue are not rebuilt by this admin replacement.</p>`);else content=`<section class="help-hero"><p class="eyebrow">START HERE / ONE ORDER</p><h2>Take one artwork from order to delivery.</h2><p>Confirm the payment, reserve materials, print, check, pack and deliver. Each action stays in the selected order's workspace. Simulate external events only when the journey needs them.</p>${actions(button('story','Start normal order',{n:2}),button('restart-scenario','Restart current scenario',{},'button secondary'))}</section>`+panel('Choose the next scenario',form('scenario-picker',select('scenario','Guided scenario',guided,S.state.ui2?.scenario||2),'Start this scenario'))+details('Advanced acceptance scenarios',A.table('Remaining isolated demonstrations',['Scenario','Start'],window.AdminWireframeStories.map(([title],n)=>[esc('US'+String(n+1).padStart(2,'0')+' / '+title),button('story','Start scenario',{n:n+1},'button secondary small-button')])))+panel('Files in this prototype',`<p>Product images and shared images are public assets. Private print originals and approval files are encrypted separately and never included in public-image downloads.</p><p>Uploads belong to this browser and website address. Use Staff & Access to back up or restore them. A scenario restart preserves your catalogue, staff and uploaded files; it resets demo orders, customers, cases and messages.</p>`+actions(link('staff','Backups & private vault','button secondary'),link('products/general','General images','button secondary')))+details('Installation & operating guide',`<p>See <a href="QUICK-START.md" target="_blank" rel="noopener">QUICK-START.md</a>. Only the admin folder is replaced. The existing repo remains responsible for serving the public site and its approved assets.</p>`);
  return A.heading('Help & demo','Review one situation at a time.',`<nav class="inline-tabs" aria-label="Help views">${[['demos','Guided demos'],['coverage','Capability coverage'],['scope','Scope']].map(([id,t])=>`<a href="#help?view=${id}"${view===id?' aria-current="page"':''}>${t}</a>`).join('')}</nav>`+content);
 };
 A.handlers.story=({n})=>{n=Number(n);if(!Number.isInteger(n)||n<1||n>23)throw Error('Choose a valid scenario.');modal('Start this scenario?','Current demonstration orders, customers, cases and messages will reset. Your catalogue, uploaded files, vault and staff records are kept. Public website data is unchanged.',notice(window.AdminWireframeStories[n-1][0],n===4||n===13?'This particular scenario uses the minimum two related records needed to test the situation.':'Only the records needed for this scenario will appear.')+check('restart','Replace the current demonstration records'),()=>{},'Start scenario');const dialog=document.querySelector('dialog');const f=dialog.querySelector('form');f.onsubmit=async e=>{e.preventDefault();if(f.dataset.busy)return;f.dataset.busy='1';try{if(!new FormData(f).get('restart'))throw Error('Confirm replacing the current demonstration records.');window.StudioState.startScenario(n);if(n===17)A.handlers['import-sample']();dialog.close();A.clearDirty();location.hash=routeScenario(n);A.render();A.toast('Scenario started. Catalogue and uploaded files were preserved.');}catch(err){const box=f.querySelector('#modal-error');box.hidden=false;box.textContent=err.message;}finally{delete f.dataset.busy;}};};
 A.forms['scenario-picker']=d=>A.handlers.story({n:Number(d.scenario)});
 A.handlers['restart-scenario']=()=>A.handlers.story({n:S.state.ui2?.scenario||2});
 A.handlers.reset=A.handlers['restart-scenario'];
 // Isolated communication scenarios need only their own message/case, not six orders.
 const start=window.StudioState.startScenario;window.StudioState.startScenario=function(n){const s=start(n),o=s.orders[0];if(n===14)S.mutate('DEMO','Prepare one customer enquiry',()=>{s.cases=[{id:'CS-DEMO',order:o.id,customer:o.customer,subject:'When will my artwork arrive?',source:'Email - manually captured',owner:S.names.owner,priority:'Normal',status:'Open',verified:false,notes:[],replies:[],due:today,type:'Enquiry'}];S.syncCaseTask(s.cases[0]);});if(n===15)S.mutate('DEMO','Prepare one failed milestone message',()=>{s.messages=[{id:'MSG-DEMO',order:o.id,item:o.items[0].id,kind:'Order confirmation',status:'Failed',attempts:3,template:'confirmation-v1',recipient:s.customers[0].email}];});return s;};
 // Only the owner is shown in default-session login. Role testing lives in US20.
 A.screens['settings/login']=()=>A.heading('Open your demo workspace','Local sign-in preview. Do not use a real password.',panel('Owner session',form('login','<input type="hidden" name="role" value="owner">'+field('code','Sample access code','','text','Enter 123456. This is not real authentication.'),'Open owner demo'))+actions(button('owner-recover','Owner recovery preview',{},'button secondary')));
 const originalAfter=A.afterRender;A.afterRender=()=>{originalAfter();document.querySelectorAll('dialog select[name=owner]').forEach(el=>{el.innerHTML=`<option value="${esc(S.names.owner)}">You (Owner)</option>`;});};
 window.StudioAdmin={validateRestore,bounds,routeScenario};
})();
/* Saved list views retain their query in the consolidated screen. */
(() => {
 const A=window.AdminUI,S=A.S;
 A.handlers['save-view']=()=>A.modal('Save the current order view','Keep this search, status and sort together.',A.field('name','View name','My working orders'),d=>S.mutate('VIEWS','Save order view',()=>S.state.views.push({name:d.name,query:A.params.toString()})),'Save view');
 A.handlers['load-view']=({i})=>{const v=S.state.views[i];if(!v)throw Error('Saved view not found.');if(v.query!==undefined)location.hash='orders'+(v.query?'?'+v.query:'');else {const f=v.filters||{};location.hash=window.StudioUI.query('orders',{q:f.q||'',status:f.status||'All'});}};
})();
