// Design traceability only. AF1 remains the canonical requirements document.
window.AdminWireframeScope = [
 ['O1','Today, search and organised work','orders',[1,21]],
 ['O2','The complete order record','orders/record',[2,3,6,9]],
 ['O3','Razorpay payment control','orders/payment',[3,4,12]],
 ['O4','Production, reservations and deadlines','orders/job',[2,4,5,7,18]],
 ['O5','Inspection and packing','orders/quality',[2,7,9]],
 ['O6','Shiprocket and delivery exceptions','orders/parcel',[2,6,8,9,10]],
 ['O7','Changes, holds and cancellations','orders/change',[5,6]],
 ['O8','Refunds and linked replacements','orders/refund',[9,11,12]],
 ['O9','Settlements, disputes and documents','orders/settlements',[2,9,12,19]],
 ['C1','Customer directory and history','customers/profile',[6,13,14]],
 ['C2','Contact preferences and privacy work','customers/privacy',[13]],
 ['P1','Catalogue, variants and collections','products/artwork',[16,17]],
 ['P2','Images, rights and production files','products/files',[2,7,16]],
 ['P3','Simple materials and suppliers','products/material',[4,18]],
 ['P4','Safe imports and exports','products/import',[17,19]],
 ['S1','Basic requests and approved replies','support/case',[10,11,13,14]],
 ['S2','Damage, returns and claim resolution','support/claim',[11]],
 ['S3','Necessary automatic messages','support/messages',[2,9,15]],
 ['R1','Sales and money that reconcile','reports/sales',[9,11,19]],
 ['R2','Operational improvement and weekly summary','reports/operations',[1,18,19]],
 ['G1','Staff security and protected data','settings/access',[13,17,20]],
 ['G2','Business rules and integrations','settings/rules',[6,22,23]],
 ['G3','Audit, approvals and safe edits','settings/activity',[5,7,12,16,17,20,21]],
 ['G4','Small, reliable automation','settings/automation',[2,3,8,12,15,21]],
 ['G5','Monitoring and recovery','settings/system',[15,20,21]],
 ['G6','Readiness and proof of completion','settings/readiness',[21,22]]
];
window.AdminWireframeStories = [
 ['A quiet morning with a clear next action','orders'],
 ['Meera’s order goes right from payment to delivery','orders/record?stage=0'],
 ['The browser closes after payment','orders/payment?state=recovered'],
 ['Two customers want the last black frame','products/material?state=shortage'],
 ['Cancellation meets production start','orders/change?state=conflict'],
 ['An address or frame needs correcting','orders/change'],
 ['The frame fails inspection','orders/quality?state=failed'],
 ['A booking succeeds but the screen times out','orders/parcel?state=unknown'],
 ['Two artworks, two parcels and a partial remedy','orders/record?id=AS-1003'],
 ['The courier cannot deliver','orders/parcel?state=failed'],
 ['Transit damage, replacement and courier compensation','support/claim'],
 ['Two staff try to refund the same payment','orders/refund?state=conflict'],
 ['A shared phone number and a privacy request','customers/privacy'],
 ['A useful reply without a full helpdesk','support/case'],
 ['A message fails after dispatch','support/messages?state=failed'],
 ['A new artwork is almost ready','products/artwork?state=incomplete'],
 ['Spreadsheet errors and a concurrent edit','products/import'],
 ['A supplier delivery is late','products/material?state=shortage'],
 ['Friday’s money does not match','orders/settlements'],
 ['A packing colleague opens a finance link','settings/access?state=denied'],
 ['A busy day, a crash and a safe recovery','settings/system'],
 ['Assess the system before accepting live V1','settings/readiness'],
 ['Three dedicated tools stay on hold','tools']
];
