(()=>{
 const script=document.currentScript,root=new URL('../',script.src),data=window.AalishaanData;if(!data)return;
 const names={white:'White',black:'Black','antique-gold':'Antique Gold'},key='aalishaanProductBag';let memory=[],persistent=true;
 const money=n=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(n);
 const safe=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const url=p=>new URL(p,root).href;
 function normalize(items){const merged=new Map();for(const i of Array.isArray(items)?items:[]){const p=data.products.find(p=>p.slug===i?.slug);if(!p||!Object.hasOwn(names,i.frame)||!Number.isInteger(i.quantity)||i.quantity<1)continue;const id=p.slug+':'+i.frame,existing=merged.get(id);if(existing)existing.quantity=Math.min(99,existing.quantity+i.quantity);else merged.set(id,{slug:p.slug,title:p.title,orientation:p.orientation,frame:i.frame,quantity:Math.min(99,i.quantity),image:p.frames[i.frame].image.src});}return [...merged.values()];}
 function read(){if(!persistent)return memory;try{memory=normalize(JSON.parse(localStorage.getItem(key)||'[]'));return memory;}catch{persistent=false;return memory;}}
 function save(items){memory=normalize(items);try{localStorage.setItem(key,JSON.stringify(memory));persistent=true;}catch{persistent=false;}queueMicrotask(render);window.dispatchEvent(new Event('bagchange'));return persistent;}
 const subtotal=items=>items.reduce((n,i)=>n+data.prices[i.frame]*i.quantity,0);
 function rows(items,edit=false){if(document.body.classList.contains('commerce-page'))return commerceRows(items,edit);return items.map((i,n)=>`<article class="bag-row pd-bag-item"><img src="${url(i.image)}" alt="${safe(i.title)}"><div><h3><a href="${url('pages/artworks/'+i.slug+'/index.html')}">${safe(i.title)}</a></h3><p>A2 ${safe(i.orientation)} · ${names[i.frame]} · ${money(data.prices[i.frame])} each · Quantity ${i.quantity} · ${money(data.prices[i.frame]*i.quantity)}</p>${edit?`<div class="bag-controls"><label>Frame<select data-frame="${n}">${Object.entries(names).map(([k,v])=>`<option value="${k}" ${k===i.frame?'selected':''}>${v}</option>`).join('')}</select></label><label>Quantity<input aria-label="Quantity for ${safe(i.title)}" data-quantity="${n}" type="number" min="1" max="99" value="${i.quantity}"></label><button data-remove="${n}">Remove</button></div>`:`<p>Quantity ${i.quantity}</p>`}<p><strong>${money(data.prices[i.frame]*i.quantity)}</strong></p></div></article>`).join('');}

 function commerceRows(items,edit){return items.map((i,n)=>`<article class="bag-row"><img src="${url(i.image)}" alt="${safe(i.title)} in a ${names[i.frame]} frame"><div><h3><a href="${url('pages/artworks/'+i.slug+'/index.html')}">${safe(i.title)}</a></h3><p>A2 ${safe(i.orientation)} &middot; ${names[i.frame]} frame</p>${edit?`<div class="bag-controls"><label>Frame<select aria-label="Frame for ${safe(i.title)}" data-frame="${n}">${Object.entries(names).map(([k,v])=>`<option value="${k}" ${k===i.frame?'selected':''}>${v}</option>`).join('')}</select></label><label>Quantity<input aria-label="Quantity for ${safe(i.title)}" data-quantity="${n}" type="number" min="1" max="99" value="${i.quantity}"></label><button data-remove="${n}" aria-label="Remove ${safe(i.title)}">Remove</button></div>`:`<p>Quantity ${i.quantity}</p>`}<p class="bag-price"><strong>${money(data.prices[i.frame]*i.quantity)}</strong>${i.quantity>1?` <small>(${money(data.prices[i.frame])} each)</small>`:''}</p></div></article>`).join('');}
 function render(){const items=read(),count=items.reduce((n,i)=>n+i.quantity,0);document.querySelectorAll('[data-open="cart-drawer"]').forEach(b=>{b.setAttribute('aria-label',`Open cart, ${count} items`);const badge=b.querySelector('.cart-count');if(badge)badge.textContent=count;});
 const drawer=document.querySelector('#cart-drawer .drawer__body');if(drawer){drawer.innerHTML=`<div data-bag-items>${items.length?rows(items):'<p class="pd-bag-empty">Your cart is empty. Choose an artwork and its frame finish to add it here.</p>'}</div>${!persistent?'<p role="status">Your selection is kept on this page only. Enable browser storage before continuing to checkout.</p>':''}<p><a class="button button--primary" href="${url(items.length?'pages/checkout/index.html':'shop-all/index.html')}">${items.length?'Continue to checkout':'Explore artworks'}</a></p>${items.length?`<p><a href="${url('pages/cart/index.html')}">Edit your bag</a></p>`:''}`;drawer.querySelectorAll('.bag-row').forEach((row,index)=>{const remove=document.createElement('button');remove.type='button';remove.textContent='Remove';remove.setAttribute('aria-label','Remove '+items[index].title);remove.style.cssText='min-height:44px;background:transparent;border:0;text-decoration:underline;cursor:pointer';remove.onclick=()=>{items.splice(index,1);save(items);document.querySelector('#cart-drawer [data-close]')?.focus();};row.lastElementChild.append(remove);});}
 const empty=`<h2>Your bag is empty.</h2><p>Choose an artwork and frame, or add a sample on the bag page to explore checkout.</p><a class="text-link" href="${url('shop-all/index.html')}">Explore artworks</a>`;
 const cart=document.querySelector('#cart-page-items');if(cart){cart.innerHTML=items.length?rows(items,true):empty;cart.querySelectorAll('[data-frame]').forEach(el=>el.onchange=()=>{items[+el.dataset.frame].frame=el.value;save(items);queueMicrotask(()=>cart.querySelector(`[data-frame="${el.dataset.frame}"]`)?.focus());});cart.querySelectorAll('[data-quantity]').forEach(el=>el.onchange=()=>{items[+el.dataset.quantity].quantity=Math.max(1,Math.min(99,Math.floor(+el.value)||1));save(items);queueMicrotask(()=>cart.querySelector(`[data-quantity="${el.dataset.quantity}"]`)?.focus());});cart.querySelectorAll('[data-remove]').forEach(el=>el.onclick=()=>{items.splice(+el.dataset.remove,1);save(items);queueMicrotask(()=>{const next=cart.querySelector('[data-remove]')||document.querySelector('#sample-bag');next?.focus();});});}
 const checkout=document.querySelector('#checkout-items');if(checkout)checkout.innerHTML=items.length?rows(items):empty;
 document.querySelectorAll('[data-subtotal]').forEach(el=>el.textContent=money(subtotal(items)));
 const button=document.querySelector('#checkout-form [data-checkout-next],#checkout-form:not([data-guided-checkout]) button');if(button)button.disabled=!items.length;
 }
 window.AalishaanBag={read,save,rows,subtotal,money,url,normalize,isPersistent:()=>persistent};
 // Product's established gallery/add controls remain unchanged; refresh after their write.
 document.addEventListener('click',e=>{if(e.target.closest('[data-add],[data-open="cart-drawer"]'))setTimeout(render,0);});
 window.addEventListener('storage',render);render();
 const style=document.createElement('style');style.textContent='#cart-drawer .bag-row{display:grid;grid-template-columns:72px 1fr;gap:14px;padding:18px 0;border-bottom:1px solid #ddd}#cart-drawer .bag-row img{width:72px;height:90px;object-fit:contain}#cart-drawer .bag-row h3{font-size:18px;margin:0}#cart-drawer .bag-row p{font-size:13px;line-height:1.6}';document.head.append(style);
})();

 document.querySelectorAll('.newsletter-form').forEach(form=>{form.querySelector('button[type=submit]').disabled=false;form.addEventListener('submit',e=>{e.preventDefault();form.querySelector('.newsletter-status').textContent='Signup preview complete. No subscription has been created.';});});
