/* Single-page checkout and tracking previews; no live transactions. */
(()=>{
 const $=s=>document.querySelector(s),bag=window.AalishaanBag,delivery=window.AalishaanDelivery;if(!bag||!delivery)return;
 const safe=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 $('#sample-bag')?.addEventListener('click',()=>{const p=window.AalishaanData.products[0],items=bag.read(),same=items.find(i=>i.slug===p.slug&&i.frame===p.suggestedFrame);if(same)same.quantity++;else items.push({slug:p.slug,frame:p.suggestedFrame,quantity:1});bag.save(items);$('#bag-status').textContent='Sample artwork added.';});
 if($('#cart-page-items')){const update=()=>{const empty=!bag.read().length;$('#checkout-link').hidden=empty;$('#sample-bag').hidden=!empty;};update();window.addEventListener('bagchange',update);}
 const form=$('#checkout-form');
 if(form){
  const status=$('#checkout-status'),pin=form.elements.pin,next=$('[data-checkout-next]');let checked=null,submitting=false;
  const places={'110001':['New Delhi','Delhi'],'400001':['Mumbai','Maharashtra'],'560001':['Bengaluru','Karnataka'],'600001':['Chennai','Tamil Nadu'],'700001':['Kolkata','West Bengal'],'411001':['Pune','Maharashtra']};
  function place(){const inputs=[form.elements.city,form.elements.state];for(const input of inputs)if(input.dataset.autoValue&&input.value===input.dataset.autoValue){input.value='';delete input.dataset.autoValue;}const p=places[pin.value];if(p)inputs.forEach((input,i)=>{if(!input.value){input.value=p[i];input.dataset.autoValue=p[i];input.removeAttribute('aria-invalid');const error=$('#error-'+input.name);if(error)error.textContent='';}});}
  function checkPin(){checked=delivery.check(pin.value);pin.setAttribute('aria-invalid',String(checked.status!=='serviceable'));$('#checkout-delivery').innerHTML=delivery.describe(checked,{compact:true});$('#checkout-delivery').dataset.status=checked.status;if(checked.status!=='invalid')delivery.save(checked);place();return checked.status==='serviceable';}
  const saved=delivery.read();if(saved){pin.value=saved.pincode;checkPin();}
  pin.addEventListener('input',()=>{pin.value=pin.value.replace(/\D/g,'').slice(0,6);checked=null;delivery.clear();if(pin.value.length===6)checkPin();else{$('#checkout-delivery').textContent='Enter all six digits to check delivery.';place();}});
  form.addEventListener('input',e=>{const err=$('#error-'+e.target.name);if(err)err.textContent='';e.target.removeAttribute('aria-invalid');status.textContent='';});
  $('#checkout-sample').onclick=()=>{for(const [k,v] of Object.entries({name:'Sample Guest',email:'guest@example.com',phone:'9000000000',pin:pin.value||'110001',address:'12 Sample Street',address2:'',city:'',state:''})){form.elements[k].value=v;form.elements[k].removeAttribute('aria-invalid');const err=$('#error-'+k);if(err)err.textContent='';}checkPin();status.textContent='Sample details filled. Nothing is sent or saved.';};
  function validate(){let first=null;for(const input of form.querySelectorAll('input:not([type=radio])')){const mobile=input.value.replace(/[\s()+-]/g,'').replace(/^91(?=\d{10}$)/,'');const valid=input.checkValidity()&&(!input.required||input.value.trim())&&(input.name!=='phone'||/^[6-9]\d{9}$/.test(mobile));input.setAttribute('aria-invalid',String(!valid));$('#error-'+input.name).textContent=valid?'':input.name==='email'?'Enter a valid email address.':input.name==='phone'?'Enter a valid 10-digit Indian mobile number.':input.name==='pin'?'Enter a six-digit PIN code.':'Please complete this field.';if(!valid&&!first)first=input;}if(pin.value.length===6&&!checkPin()){pin.setAttribute('aria-invalid','true');pin.focus();status.textContent=checked.status==='unserviceable'?'Delivery is unavailable for this sample PIN code. Try another address.':'Delivery availability could not be checked. Try again before continuing.';return false;}if(first){first.focus();status.textContent='Please check the highlighted details.';return false;}if(!checkPin()){pin.setAttribute('aria-invalid','true');pin.focus();status.textContent=checked.status==='unserviceable'?'Delivery is unavailable for this sample PIN code. Try another address.':'Delivery availability could not be checked. Try again before continuing.';return false;}return true;}
  form.onsubmit=e=>{e.preventDefault();if(submitting)return;const items=bag.read();if(!items.length){status.textContent='Your bag is empty.';return;}if(!validate())return;submitting=true;next.disabled=true;
   const order={reference:'AS-PREVIEW-001',createdAt:new Date().toISOString(),items,subtotal:bag.subtotal(items),payment:form.elements.payment.value,delivery:{pincode:pin.value,status:checked.status,estimate:checked.estimate,range:delivery.range(checked)}};
   try{sessionStorage.setItem('aalishaanOrderPreview',JSON.stringify(order));}catch{status.textContent='Your browser could not save the sample order. Allow session storage and try again.';submitting=false;next.disabled=false;return;}location.href=bag.url('pages/order/demo/index.html');
  };
  const refresh=()=>{const empty=!bag.read().length;form.hidden=empty;$('#checkout-empty').hidden=!empty;next.disabled=empty||submitting;};refresh();window.addEventListener('bagchange',()=>queueMicrotask(refresh));window.addEventListener('storage',()=>queueMicrotask(refresh));window.addEventListener('pageshow',()=>{submitting=false;refresh();});
 }
 const confirmation=$('#confirmation');if(confirmation){try{
  const order=JSON.parse(sessionStorage.getItem('aalishaanOrderPreview')||'null'),items=bag.normalize(order?.items);
  if(items.length&&order.reference==='AS-PREVIEW-001'){
   const pin=/^[1-9][0-9]{5}$/.test(order.delivery?.pincode||'')?order.delivery.pincode:'Not checked';
   const date=Number.isFinite(Date.parse(order.createdAt))?new Date(order.createdAt).toLocaleString('en-IN',{dateStyle:'medium',timeStyle:'short'}):'Sample date';
   confirmation.innerHTML=`<span class="eyebrow">Aalishaan Studio</span><h2>Your order receipt</h2><p class="flow-fine">Sample order · No payment collected</p><div class="receipt-meta">Order: <strong>${safe(order.reference)}</strong><br>Date: ${safe(date)}<br>Payment method: ${safe(order.payment)}<br>Delivery PIN: ${pin}</div>${bag.rows(items)}<dl class="flow-totals"><div><dt>Artwork subtotal</dt><dd>${bag.money(bag.subtotal(items))}</dd></div><div><dt>Shipping & tax</dt><dd>To be confirmed</dd></div><div><dt>Amount paid</dt><dd>₹0 · Sample</dd></div></dl><p class="receipt-thanks">Thank you for making room for art.</p><p class="flow-fine">info@aalishaanstudio.com<br>+91 9137624394</p>`;
   $('#receipt-actions').hidden=false;
   $('#print-receipt').onclick=()=>window.print();
   const output=$('.receipt-output'),printStatus=$('#receipt-print-status');
   if(output){output.style.setProperty('--receipt-height',confirmation.scrollHeight+'px');output.classList.add('is-printing');printStatus.textContent='Printing your receipt…';const complete=()=>{output.classList.remove('is-printing');printStatus.textContent='Your receipt is ready';};output.addEventListener('animationend',complete,{once:true});if(matchMedia('(prefers-reduced-motion: reduce)').matches)complete();}
   $('#download-receipt').onclick=async()=>{const button=$('#download-receipt');button.disabled=true;button.textContent='Preparing PDF…';try{const blob=await window.AalishaanReceiptPDF(order,items);const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='Aalishaan-'+order.reference+'-receipt.pdf';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch{printStatus.textContent='The PDF could not be created. Please use Print / Save PDF.';}finally{button.disabled=false;button.textContent='Download receipt (PDF)';}};
  }
 }catch{confirmation.innerHTML='<h2>Your receipt could not be opened.</h2><p>Return to your bag and try the sample checkout again.</p>';}}
 const tracking=$('#track-form');if(tracking){
  let mode='order';const input=tracking.elements.reference;
  const modes={order:['Order reference','e.g. AS-PREVIEW-001','Find your order ID in your confirmation email.'],awb:['Airway Bill number (AWB)','e.g. SAMPLE-AWB-001','A courier assigns an AWB when your shipment is booked. It is not available during printing or framing.'],mobile:['Mobile number','10-digit mobile number','Live tracking by phone will require verification. Use 9000000000 for this sample.']};
  document.querySelectorAll('[data-track-mode]').forEach((button,i,buttons)=>{button.onclick=()=>{mode=button.dataset.trackMode;buttons.forEach(b=>{b.setAttribute('aria-selected',String(b===button));b.tabIndex=b===button?0:-1;});$('#track-label').textContent=modes[mode][0];input.placeholder=modes[mode][1];input.value='';input.inputMode=mode==='mobile'?'tel':'text';input.removeAttribute('aria-invalid');$('#track-hint').textContent=modes[mode][2];$('#track-error').textContent='';$('#tracking-result').innerHTML='<h2>Follow every step.</h2><p>Enter your '+safe(modes[mode][0].toLowerCase())+' to find your artwork.</p>';};button.tabIndex=i?-1:0;button.onkeydown=e=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();const n=e.key==='Home'?0:e.key==='End'?2:(i+(e.key==='ArrowRight'?1:2))%3;buttons[n].click();buttons[n].focus();}};});
  function lookup(){const ref=input.value.trim().toUpperCase();const valid=mode==='order'?ref==='AS-PREVIEW-001':mode==='awb'?ref==='SAMPLE-AWB-001':ref.replace(/[\s()+-]/g,'').replace(/^91(?=\d{10}$)/,'')==='9000000000';input.setAttribute('aria-invalid',String(!valid));$('#track-error').textContent=valid?'':'No matching sample found. Check your details or explore the sample below.';if(!valid){$('#tracking-result').innerHTML='<h2>Let’s find your artwork.</h2><p>Check your details and try again.</p><a class="text-link" href="'+bag.url('pages/contact/index.html')+'">Contact & Support →</a>';return;}
   const shipped=mode==='awb';const stages=['Order confirmed','Artwork prepared','Being framed','Quality checked','Packed securely','On its way','Delivered'];const current=shipped?5:2;
   $('#tracking-result').innerHTML=`<span class="eyebrow">AS-PREVIEW-001 · Sample journey</span><h2>${stages[current]}</h2><p>${shipped?'Your artwork has been handed to the courier.':'Your artwork is taking shape. Next, we inspect the print and frame.'}</p><dl class="tracking-meta"><div><dt>Courier</dt><dd>${shipped?'Sample courier':'Awaiting assignment'}</dd></div><div><dt>AWB</dt><dd>${shipped?'SAMPLE-AWB-001':'Available after booking'}</dd></div><div><dt>Estimated delivery</dt><dd>Not yet confirmed</dd></div><div><dt>Latest update</dt><dd>Illustrative sample</dd></div></dl><ol class="tracking-timeline">${stages.map((s,i)=>`<li ${i<current?'class="done"':i===current?'aria-current="step"':''}>${s}<small>${i<current?'Complete':i===current?'Current stage':i===current+1?'Next step':'Upcoming'}</small></li>`).join('')}</ol><p class="flow-fine">Sample tracking. Live courier updates are not connected.</p>`;
  }
  tracking.onsubmit=e=>{e.preventDefault();lookup();};$('#track-sample').onclick=()=>{input.value=mode==='order'?'AS-PREVIEW-001':mode==='awb'?'SAMPLE-AWB-001':'9000000000';lookup();};const ref=new URLSearchParams(location.search).get('reference');if(ref){input.value=ref;lookup();}
 }
})();
