(()=>{
 if(document.body.classList.contains('commerce-page'))return;
 const $=s=>document.querySelector(s),bag=window.AalishaanBag;
 const search=$('#faq-search'),topic=$('#faq-topic');function filter(){let count=0;document.querySelectorAll('#questions>[data-topic]').forEach(el=>{el.hidden=!(el.textContent.toLowerCase().includes(search.value.trim().toLowerCase())&&(!topic.value||el.dataset.topic===topic.value));if(!el.hidden)count++;});$('#faq-status').textContent=`${count} answers`;$('#faq-empty').hidden=!!count;}if(search){search.oninput=filter;topic.onchange=filter;$('#faq-reset').onclick=()=>{search.value='';topic.value='';filter();search.focus();};}
 const contactButton=$('#contact-form button[type=submit],#contact-form button:not([type])');if(contactButton)contactButton.disabled=false;
 $('#contact-form')?.addEventListener('submit',e=>{e.preventDefault();$('#contact-status').textContent='Enquiry preview complete. In the live store, this would be sent to support. No message was sent or saved.';});
 const tracking=$('#track-form');if(tracking){const ref=new URLSearchParams(location.search).get('reference');if(ref)tracking.elements.reference.value=ref;$('#track-sample').onclick=()=>{tracking.elements.reference.value='AS-PREVIEW-001';tracking.requestSubmit();};tracking.onsubmit=e=>{e.preventDefault();const valid=tracking.elements.reference.value.trim().toUpperCase()==='AS-PREVIEW-001';$('#tracking-result').innerHTML=valid?'<span class="eyebrow">Sample order · AS-PREVIEW-001</span><h2>Being framed</h2><p>Illustrative progress only. No shipment or delivery date is confirmed.</p><ol class="journey"><li>Order reviewed · Complete</li><li>Archival print prepared · Complete</li><li>Framing and quality check · Current stage</li><li>Packed for dispatch · Next</li><li>On its way · Awaiting dispatch</li><li>Delivered · Awaiting delivery</li></ol>':'<h2>No sample matches that reference.</h2><p>Use AS-PREVIEW-001 to explore the demonstration. This page cannot look up live orders.</p>';tracking.elements.reference.setAttribute('aria-invalid',String(!valid));};}
 $('#sample-bag')?.addEventListener('click',()=>{const p=window.AalishaanData.products[0],items=bag.read(),same=items.find(i=>i.slug===p.slug&&i.frame===p.suggestedFrame);if(same)same.quantity++;else items.push({slug:p.slug,frame:p.suggestedFrame,quantity:1});bag.save(items);});
 $('#checkout-form')?.addEventListener('submit',e=>{e.preventDefault();const items=bag.read();if(!items.length){$('#checkout-status').textContent='Add an artwork to your bag first.';return;}const pin=e.target.elements.pin.value.trim(),d=window.AalishaanDelivery,check=d?d.check(pin):null;if(check&&(check.status==='invalid'||check.status==='unserviceable')){$('#checkout-status').textContent=check.status==='invalid'?'Enter a valid six-digit PIN code to continue.':'We can’t deliver to '+pin+' yet in this preview. Try another PIN code or contact us.';e.target.elements.pin.setAttribute('aria-invalid','true');e.target.elements.pin.focus();return;}if(check&&check.status==='serviceable')d.save(check);const snapshot={reference:'AS-PREVIEW-001',items,subtotal:bag.subtotal(items),payment:e.target.elements.payment.value,delivery:check?{pincode:pin,status:check.status,estimate:check.estimate||null,range:check.estimate?d.range(check):''}:null};try{sessionStorage.setItem('aalishaanOrderPreview',JSON.stringify(snapshot));}catch{$('#checkout-status').textContent='Browser storage is unavailable. Your selection remains in the bag; confirmation cannot be carried to another page.';return;}location.href=bag.url('pages/order/demo/index.html');});
 const confirmation=$('#confirmation');if(confirmation){try{const order=JSON.parse(sessionStorage.getItem('aalishaanOrderPreview')||'null');if(order&&Array.isArray(order.items)&&order.items.length&&Number.isFinite(order.subtotal)){const items=bag.normalize(order.items);confirmation.innerHTML='<span class="eyebrow">AS-PREVIEW-001 · Sample confirmation</span><h2>Your selection, all together.</h2>'+bag.rows(items)+`<p><strong>Artwork subtotal: ${bag.money(order.subtotal)}</strong></p><p>Payment: not collected. Delivery charges: to be confirmed.</p><p>Sample destination: 12 Sample Street, New Delhi, ${/^[1-9][0-9]{5}$/.test(order.delivery&&order.delivery.pincode||'')?order.delivery.pincode:'110001'}.${order.delivery&&order.delivery.status==='serviceable'&&order.delivery.range?' Estimated delivery '+String(order.delivery.range).replace(/[<>&]/g,'')+' (sample estimate).':order.delivery&&order.delivery.status==='error'?' Delivery estimate to be confirmed after ordering (sample).':''}</p><p>Your bag is kept intact so you can continue trying different selections.</p>`;}}catch{}}
 $('#clear-preview')?.addEventListener('click',()=>{try{for(const k of Object.keys(localStorage))if(['aalishaanProductBag','aalishaanDeliveryCheck','aalishaanIntakeWaitlist'].includes(k)||k.startsWith('aalishaan-wishlist-'))localStorage.removeItem(k);for(const k of Object.keys(sessionStorage))if(k==='aalishaanOrderPreview'||k.startsWith('aalishaan-frame-'))sessionStorage.removeItem(k);bag.save([]);window.AalishaanDelivery?.clear();window.dispatchEvent(new Event('wishlistchange'));$('#clear-status').textContent='Saved storefront selections cleared.';}catch{$('#clear-status').textContent='Storage is unavailable. Use your browser settings to clear saved data.';}});
})();
