/* Portable receipt PDF, generated locally from the same sample order shown on screen.
   Canvas preserves the rupee symbol and artwork names without external font/PDF dependencies. */
(()=>{
 const enc=new TextEncoder(),bytes=s=>enc.encode(s),join=chunks=>{const out=new Uint8Array(chunks.reduce((n,c)=>n+c.length,0));let offset=0;for(const c of chunks){out.set(c,offset);offset+=c.length;}return out;};
 function pdf(images){const objects=[],pages=images.map((_,i)=>3+i*3);objects[1]=bytes('<< /Type /Catalog /Pages 2 0 R >>');objects[2]=bytes(`<< /Type /Pages /Count ${pages.length} /Kids [${pages.map(n=>n+' 0 R').join(' ')}] >>`);
  images.forEach((jpeg,i)=>{const n=pages[i],commands=bytes('q 595.28 0 0 841.89 0 0 cm /Receipt Do Q');objects[n]=bytes(`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595.28 841.89] /Resources << /XObject << /Receipt ${n+2} 0 R >> >> /Contents ${n+1} 0 R >>`);objects[n+1]=join([bytes(`<< /Length ${commands.length} >>\nstream\n`),commands,bytes('\nendstream')]);objects[n+2]=join([bytes(`<< /Type /XObject /Subtype /Image /Width 1240 /Height 1754 /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length ${jpeg.length} >>\nstream\n`),jpeg,bytes('\nendstream')]);});
  const chunks=[bytes('%PDF-1.4\n')],offsets=[0];let length=chunks[0].length;for(let i=1;i<objects.length;i++){offsets[i]=length;const o=join([bytes(`${i} 0 obj\n`),objects[i],bytes('\nendobj\n')]);chunks.push(o);length+=o.length;}const start=length;chunks.push(bytes(`xref\n0 ${objects.length}\n0000000000 65535 f \n${offsets.slice(1).map(n=>String(n).padStart(10,'0')+' 00000 n \n').join('')}trailer\n<< /Size ${objects.length} /Root 1 0 R >>\nstartxref\n${start}\n%%EOF`));return new Blob([join(chunks)],{type:'application/pdf'});
 }
 window.AalishaanReceiptPDF=async(order,items)=>{
  await document.fonts.ready;const money=window.AalishaanBag.money,prices=window.AalishaanData.prices,names={white:'White',black:'Black','antique-gold':'Antique Gold'},pages=[];let canvas,ctx,y;
  function start(){canvas=document.createElement('canvas');canvas.width=1240;canvas.height=1754;ctx=canvas.getContext('2d');ctx.fillStyle='#fffdf7';ctx.fillRect(0,0,1240,1754);ctx.fillStyle='#191813';y=100;}
  function finish(){ctx.font='22px Arial';ctx.fillStyle='#68645e';ctx.fillText('Aalishaan Studio · Sample receipt · Page '+(pages.length+1),90,1685);pages.push(Uint8Array.from(atob(canvas.toDataURL('image/jpeg',.94).split(',')[1]),c=>c.charCodeAt(0)));}
  function line(text,size=28,bold=false){ctx.font=`${bold?'bold ':''}${size}px Arial`;const words=String(text).split(/\s+/);let row='';for(const word of words){if(ctx.measureText(row+' '+word).width>1060&&row){emit(row);row=word;}else row+=(row?' ':'')+word;}emit(row);function emit(t){if(y>1560){finish();start();ctx.font=`${bold?'bold ':''}${size}px Arial`;}ctx.fillStyle='#191813';ctx.fillText(t,90,y);y+=size*1.55;}}
  function rule(){if(y>1530){finish();start();}y+=14;ctx.strokeStyle='#c9c2b9';ctx.setLineDash([6,6]);ctx.beginPath();ctx.moveTo(90,y);ctx.lineTo(1150,y);ctx.stroke();ctx.setLineDash([]);y+=42;}
  start();line('AALISHAAN STUDIO',26,true);y+=30;line('Your order receipt',52,true);line('Sample order · No payment collected',25);rule();line('Order: '+order.reference);line('Date: '+(Number.isFinite(Date.parse(order.createdAt))?new Date(order.createdAt).toLocaleString('en-IN'):'Sample'));line('Payment choice: '+order.payment);line('Delivery PIN: '+(order.delivery?.pincode||'Not checked'));rule();
  items.forEach((item,i)=>{line(`${i+1}. ${item.title}`,30,true);line(`A2 ${item.orientation} · ${names[item.frame]} frame`,25);line(`${money(prices[item.frame])} × ${item.quantity} = ${money(prices[item.frame]*item.quantity)}`,27);y+=20;});rule();line('Artwork subtotal: '+money(window.AalishaanBag.subtotal(items)),30,true);line('Shipping & tax: To be confirmed',26);line('Amount paid: ₹0 — Sample',30,true);rule();line('Thank you for making room for art.',30);line('info@aalishaanstudio.com',25);line('+91 9137624394',25);finish();return pdf(pages);
 };
})();
