// R1 visual prototypes. No remote services or live transactions.
const fs=require('fs'),path=require('path');
const products=require('../data/products.json'),prices=require('../data/pricing.json');
const home=fs.readFileSync('index.html','utf8');
const header=home.slice(home.indexOf('<header class="site-header"'),home.indexOf('<main id="main">'));
const footer=home.slice(home.indexOf('<footer'),home.indexOf('<!-- ===================== OVERLAYS'));
const overlays=home.slice(home.indexOf('<div class="backdrop"'),home.indexOf('<script>\n(function'));
let common=home.slice(home.indexOf('<script>\n(function'),home.lastIndexOf('</script>')+9);
common=common.slice(0,common.indexOf('  /* ---------- wall-to-materials'))+'  window.addEventListener("scroll",stuck,{passive:true});\n})();\n</script>';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const link=(href,label,secondary=false)=>`<a class="button button--${secondary?'secondary':'primary'}" href="${href}">${label}</a>`;
const hero=(title,intro,kicker='Aalishaan Studio')=>`<section class="utility-hero"><span class="eyebrow">${kicker}</span><h1>${title}</h1><p>${intro}</p></section>`;
const card=(title,body)=>`<section class="utility-card"><h2>${title}</h2>${body}</section>`;
const faq=(q,a)=>`<details class="utility-faq"><summary>${q}</summary><p>${a}</p></details>`;
const note='<p class="preview-note">Interactive preview · No messages, orders or payments are sent. Use sample details only.</p>';
const field=(label,name,type='text',value='',attrs='')=>`<label>${label}<input name="${name}" type="${type}" value="${value}" ${attrs}></label>`;
function shell(file,title,intro,body){
 const isStudio=file==='pages/about/studio/index.html',isCommerce=/^pages\/(track|cart|checkout|order)\//.test(file),isError=/pages\/(404|500)\.html/.test(file);
 const isHelp=!isStudio&&/^pages\/(about|help|contact|policies)\//.test(file),isArticle=file.includes('/policies/'),isHub=file==='pages/about/index.html',isBrand=isHelp&&!file.includes('/contact/');
 if(isHelp){
  const search='<form class="help-search" action="pages/about/index.html" role="search"><svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="10" cy="10" r="7"></circle><path d="m15 15 6 6"></path></svg><label class="visually-hidden" for="help-search">Search studio information and policies</label><input id="help-search" type="search" name="q" placeholder="Search for answers..."><button type="submit">Search</button></form>';
  const banner='<section class="help-banner'+(isHub?' help-banner--editorial':'')+'">'+(isHub?'<h1>About Aalishaan Studio</h1><p>Get to know the studio. Find answers, policies and support.</p>':'')+search+'</section>';
  const breadcrumb=isHub?'':'<nav class="help-breadcrumb" aria-label="Breadcrumb"><a href="pages/about/index.html">About</a><span aria-hidden="true">&rsaquo;</span><span aria-current="page">'+title+'</span></nav>';
  body=banner+breadcrumb+(!isHub&&!body.startsWith('<section class="utility-hero">')?hero(title,intro,''):'')+body;
 }
 const prefix=path.posix.relative(path.posix.dirname(file),'.')+'/';
 const remap=s=>s.replace(/href="#top"/g,'href="index.html"').replace(/(href|src|action)="(?!https?:|mailto:|tel:|#)([^"]+)"/g,(_,a,v)=>`${a}="${prefix}${v}"`).replace(/srcset="([^"]+)"/g,(_,v)=>`srcset="${v.split(',').map(c=>c.trim().replace(/^(?!https?:|\/)(\S+)/,`${prefix}$1`)).join(', ')}"`);
 const html=`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title} | Aalishaan Studio</title><meta name="description" content="${esc(intro)}"><link rel="stylesheet" href="${prefix}shared/browse-home.css"><link rel="stylesheet" href="${prefix}shared/home-r2.css"><link rel="stylesheet" href="${prefix}shared/browse.css"><link rel="stylesheet" href="${prefix}shared/pending.css">${isHelp?`<link rel="stylesheet" href="${prefix}shared/about-hub.css">`:""}${isBrand||isStudio||isCommerce||isError?`<link rel="stylesheet" href="${prefix}shared/storefront-r7.css">`:""}<link rel="stylesheet" href="${prefix}shared/gallery-r8.css"><link rel="stylesheet" href="${prefix}shared/revision-r9.css"><link rel="stylesheet" href="${prefix}shared/revision-r11.css">${isCommerce?`<link rel="stylesheet" href="${prefix}shared/intake-e10.css">`:""}</head><body class="browse-page utility-page${isHelp?' help-page':''}${isArticle?' help-article-page':''}${isBrand?' help-brand':''}${isStudio?' studio-page':''}${isCommerce?' commerce-page':''}${isError?' recovery-page':''}"><a class="skip-link" href="#main">Skip to main content</a>${remap(header)}<main id="main" class="container utility-main">${remap(body)}<noscript>${isCommerce?'<style>#checkout-form,.checkout-steps,#track-form,.flow-sample{display:none}</style>':''}<p>Interactive previews need JavaScript. You can still read these pages and <a href="${prefix}shop-all/index.html">browse the artworks</a>.</p></noscript></main>${remap(footer+overlays)}${common}<script src="${prefix}shared/prototype-data.js"></script><script src="${prefix}shared/bag.js"></script><script src="${prefix}shared/delivery.js"></script><script src="${prefix}shared/pending.js"></script>${isHelp?`<script src="${prefix}shared/about-hub.js"></script>`:""}${isCommerce?`<script src="${prefix}shared/receipt-pdf.js"></script><script src="${prefix}shared/commerce-r9.js"></script><script src="${prefix}shared/intake-e10.js"></script>`:""}</body></html>`;
 fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,html);
}
const write=(slug,title,intro,body)=>shell(`pages/${slug}/index.html`,title,intro,hero(title,intro)+body);
const p=products.find(p=>p.slug==='the-blossom-over-the-closed-window')||products[0];
const studio=`<div class="utility-split about-feature"><figure><img src="${p.frames[p.suggestedFrame].image.src}" alt="${esc(p.title)} in its suggested frame"><figcaption>${esc(p.title)} · Framed archival print</figcaption></figure><div><span class="eyebrow">About the studio</span><h2>A story. A surface. A place in your home.</h2><p>Explore 22 artworks across three collections and eleven art styles. From quiet landscapes to imagined harbours, each piece offers a different atmosphere to live with.</p><p>The artwork’s visual tradition shapes the image. The object you receive is a framed archival giclée print, made to order.</p>${link('pages/collections/index.html','Explore the collections')}</div></div><div class="utility-grid">${card('The print','<p>12-colour pigment inks on Hahnemühle Museum Etching 350 gsm paper. Every print is A2, in the orientation of the artwork.</p>')}${card('The frame','<p>Ornately carved solid wood, acrylic glazing and fitted hanging hardware. Choose White, Black or Antique Gold.</p>')}${card('Your wall','<p>Start with the story, then explore the colours and rooms suggested on each artwork page. Outer frame dimensions will be confirmed before ordering.</p>')}</div>`;
const questions=[['Artwork & print','What exactly am I buying?','A made-to-order, framed A2 archival giclée print, not an original painting. The textures and metallic effects you see in the artwork are reproduced in print.'],['Artwork & print','What paper and inks do you use?','Hahnemühle Museum Etching 350 gsm paper and 12-colour pigment inks.'],['Size & frame','What size is A2?','Portrait prints measure 42 × 59.4 cm; landscape prints measure 59.4 × 42 cm. These are print dimensions. Outer frame dimensions will be confirmed before ordering.'],['Size & frame','Which frames can I choose?','White ₹19,000, Black ₹21,000 or Antique Gold ₹23,000. Each is ornately carved solid wood with acrylic glazing and fitted hanging hardware.'],['Ordering','How many artworks are available?','Explore 22 artworks, three collections and eleven art styles. Choose a frame on the artwork page, then add it to your bag.'],['Ordering','Can I place an order here?','This is a visual preview. You can explore a sample checkout, but no order is placed and no payment is collected.'],['Ordering','Can I pay cash on delivery?','We accept online payment only: UPI, cards, net banking and wallets through Razorpay. If you’d prefer to pay another way, message us on WhatsApp at +91 9137624394 and we’ll help.'],['Ordering','What happens if ordering is paused?','When the studio is working through a large number of orders we may pause new orders for a short while. Leave your email or mobile number on the bag or checkout page and we’ll tell you the moment ordering reopens. Your bag will be waiting for you.'],['Delivery & care','Where do you deliver?','Delivery is planned across India. Enter your PIN code on any artwork page, in your bag or at checkout to see a sample serviceability check and delivery estimate. Shipping charges, final serviceable locations and production and delivery estimates will be confirmed before orders open.'],['Delivery & care','How do I care for my print?','Hang away from direct sunlight and moisture. Use a soft, dry cloth on the frame; never spray cleaning products directly onto the glazing.'],['Support','What if my artwork arrives damaged?','Keep photographs of the artwork and packaging. Full reporting, replacement and return conditions will be confirmed before orders open.'],['Support','Can I cancel or request a refund?','Eligibility, cut-offs and refund timings are still being finalised. See the policy pages for the current status.'],['Support','Are gifting options available?','Gift notes, special packaging and delivery to a recipient are not yet confirmed. You can preview a gifting enquiry on the Contact page.']];
shell('pages/contact/index.html','Contact & Support','',`<div class="utility-split"><form id="contact-form" class="utility-card utility-form"><p class="flow-fine">Sample form. Use sample details only; no message is sent or saved.</p>${field('Name','name','text','','required autocomplete="off"')}${field('Email','email','email','','required autocomplete="off"')}<label>What can we help with?<select name="topic"><option>Choosing an artwork</option><option>Gifting</option><option>Order question</option><option>Damage or replacement</option><option>Privacy question</option></select></label><label>Your message<textarea name="message" required minlength="10" rows="5" placeholder="Tell us what you have in mind."></textarea></label><button class="button button--primary" disabled>Preview enquiry</button><p role="status" id="contact-status"></p></form><aside>${card('Before you write','<ul class="contact-points"><li>For artwork advice, include its name and your preferred frame finish.</li><li>For an order question, include your order reference.</li><li>Describe the issue or the help you need.</li><li>For damage, keep photographs of the piece and packaging ready.</li></ul><p><a href="mailto:info@aalishaanstudio.com">info@aalishaanstudio.com</a><br><a href="tel:+919137624394">+91 9137624394</a></p>')}${card('Find a quick answer',`${link('pages/help/index.html','Read the FAQs',true)} <p>Sizes, materials, frame finishes and care, all in one place.</p>`)}</aside></div>`);
const policies={
 shipping:['Shipping & Delivery','Made to order. Delivered across India.',[['Where we deliver','Our delivery scope is India. You can check a PIN code on any artwork page for a sample serviceability result and delivery estimate. Specific serviceable locations and courier coverage will be confirmed before orders open.'],['Production and delivery','Each piece is printed and framed after ordering. Production, dispatch and transit estimates are still being finalised.'],['Charges and address changes','Delivery charges and the address-correction process will be shown before ordering becomes available.'],['Receiving your artwork','Keep photographs of the packaging and artwork if something arrives damaged. Reporting and resolution conditions will be published before orders open.']]],
 cancellation:['Cancellation','A clear place to understand changes to an order.',[['Requesting a change','Request a correction as early as possible. The available request channels will be published before orders open.'],['Eligibility and production','Cancellation eligibility, production cut-offs and any fees are still being finalised. Made-to-order status alone does not define these terms.'],['What happens next','The final policy will explain how a request is confirmed and how any eligible refund is handled.']]],
 returns:['Returns & Replacements','Help when something is not as expected.',[['An issue with your artwork','Damage, the wrong artwork or a material defect are useful details to describe in a support enquiry.'],['Photographs and packaging','Keep photographs of the artwork and its packaging. Tell support if the packaging is too damaged to reuse. Evidence requirements will be confirmed before orders open.'],['Review and resolution','Eligibility, reporting periods, collection arrangements, costs and replacement or refund conditions are being finalised.'],['Colour and care','Screens and lighting can make colours appear different. Keep prints away from direct sunlight and moisture.']]],
 refunds:['Refunds','Understanding an eligible refund.',[['When this applies','Refund eligibility will be defined alongside the cancellation and returns policies before orders open.'],['Amounts and method','The treatment of partial refunds, delivery charges and refund methods is still being finalised.'],['Timing','Initiation and payment-provider processing are separate stages. Neither timeline is confirmed yet.'],['Payment questions','A failed or reversed payment is different from a voluntary refund. This prototype does not take payments.']]],
 privacy:['Privacy','How this preview handles information.',[['Scope','This page describes the current visual prototype. The live store’s seller identity, privacy contact and full data practices will be published before launch.'],['Forms and payments','Contact and checkout do not send information. Use sample details only. Address and contact fields are not saved by the preview. No payment information is requested.'],['Browser storage','Your selected artworks, wishlist and the PIN code you check for delivery can be remembered in this browser. The order preview is stored for the browser session and contains artwork selections, a payment-method label and that PIN code, not personal details. If you try the waiting-list preview shown while ordering is paused, the details you enter are kept only in this browser; nothing is sent.'],['Your controls','You can clear this preview’s saved selections on the Cookies page or through your browser settings.'],['Future policy','Live providers, retention periods and a privacy-request route have not been confirmed. This page does not describe an operating customer database.']]],
 terms:['Terms & Conditions','What you are exploring and what you would receive.',[['This preview','This site is a visual demonstration. Adding to a bag or viewing confirmation does not create an order or a payment.'],['The artwork','You receive an archival giclée reproduction, not an original painting. Marks, textures and metallic effects are reproduced in print.'],['Size, frame and price','A2 prints come in White, Black or Antique Gold frames. Published artwork prices are ₹19,000, ₹21,000 and ₹23,000 respectively. Outer dimensions, delivery charges and tax treatment will be confirmed before ordering.'],['Orders and policies','Order acceptance, cancellation, returns and refund terms are not yet final. Read the corresponding pages for their current status.'],['Seller information','The seller’s legal identity, contact details and final commercial terms will be provided before live orders open.']]],
 cookies:['Cookies & Browser Storage','Simple controls for this preview.',[['What is remembered','The prototype uses browser storage for the bag, wishlist, the PIN code you check for delivery and a session order preview. It also keeps any waiting-list preview entry you submit while ordering is paused. These let you revisit your selection while exploring the site.'],['Optional services','This revision adds no analytics, advertising or payment service. No pretend consent switches are needed to use the preview.'],['Clear your preview','Clear the saved bag, wishlist, order preview and waiting-list preview entries using the control below. Your browser also provides storage controls.']]]
};
fs.writeFileSync('shared/prototype-data.js','window.AalishaanData='+JSON.stringify({products,prices}).replaceAll('<','\\u003c')+';\n');
// Only the authorised cart integration is added to completed pages.
const finished=['index.html','shop-all/index.html','product/index.html'];
for(const dir of ['pages/collections','pages/art-styles','pages/artworks','product/artworks']){for(const f of fs.readdirSync(dir,{recursive:true}))if(f.endsWith('index.html'))finished.push(dir+'/'+f.replaceAll('\\','/'));}
for(const file of finished){let html=fs.readFileSync(file,'utf8');const prefix=path.posix.relative(path.posix.dirname(file),'.');const root=prefix?prefix+'/':'';if(!html.includes('shared/bag.js'))html=html.replace('</body>',`<script src="${root}shared/prototype-data.js"></script><script src="${root}shared/bag.js"></script></body>`);fs.writeFileSync(file,html);}
console.log('Built 16 pending storefront pages and shared preview data (delivery checking carried into Cart and Checkout).');

require("./build-about-hub.cjs")({shell,questions,policies,studio});

shell("pages/about/studio/index.html","About the Studio","Bring beauty into everyday life.",require("./studio-content.cjs")());
require("./build-shop-flow.cjs")({shell,hero,link});
