module.exports=()=>{
 const field=(label,name,type,attrs)=>`<label>${label}<input name="${name}" type="${type}" ${attrs} aria-describedby="error-${name}"><span id="error-${name}" class="field-error"></span></label>`;
 return `<header class="checkout-heading"><h1>Checkout</h1><p>Guest checkout · Your artwork, made for you.</p><p class="flow-fine">Design preview. Use sample details only. No order is placed or payment collected.</p></header><section id="checkout-empty" class="flow-panel" hidden><h2>Your bag is empty.</h2><a class="button button--primary" href="shop-all/index.html">Explore artworks</a></section><form id="checkout-form" data-guided-checkout novalidate><div class="flow-layout"><div class="checkout-fields-panel"><div class="intake-slot" data-intake-slot hidden></div><section class="flow-panel"><div class="flow-section-title"><h2>Contact & delivery</h2><button type="button" class="flow-sample" id="checkout-sample">Use sample details</button></div><div class="flow-fields">
 ${field('Full name','name','text','required autocomplete="shipping name"')}
 ${field('Email','email','email','required autocomplete="shipping email"')}
 ${field('Mobile number','phone','tel','required autocomplete="shipping tel" inputmode="tel" placeholder="10-digit mobile number"')}
 ${field('PIN code','pin','text','required autocomplete="shipping postal-code" inputmode="numeric" maxlength="6" pattern="[1-9][0-9]{5}"')}
 <p id="checkout-delivery" class="delivery-line flow-full" role="status"></p>
 ${field('Address','address','text','required autocomplete="shipping address-line1" placeholder="House / flat number, building and street"')}
 ${field('Landmark (optional)','address2','text','autocomplete="shipping address-line2"')}
 ${field('City','city','text','required autocomplete="shipping address-level2"')}
 ${field('State / Union territory','state','text','required autocomplete="shipping address-level1"')}
 </div><p class="flow-fine">India · All fields required unless marked optional.</p></section><section class="flow-panel payment-panel"><h2>Payment</h2><fieldset class="payment-choices"><legend class="visually-hidden">Choose payment method</legend>${[['UPI','Your preferred UPI app'],['Card','Credit or debit card'],['Net banking','Pay through your bank'],['Wallet','A supported wallet']].map(([t,d],i)=>`<label><input type="radio" name="payment" value="${t}" ${i?'':'checked'}><span><strong>${t}</strong><small>${d}</small></span></label>`).join('')}</fieldset><p class="flow-fine payment-policy">We accept online payment only (UPI, cards, net banking and wallets via Razorpay). Prefer to pay another way? <a href="https://wa.me/919137624394" data-whatsapp-help target="_blank" rel="noopener">Message us on WhatsApp</a> and we’ll help.</p></section></div><aside class="flow-panel flow-summary"><h2>Your order</h2><a class="text-link" href="pages/cart/index.html">Edit bag</a><div id="checkout-items"></div><dl class="flow-totals"><div><dt>Artwork subtotal</dt><dd data-subtotal></dd></div><div><dt>Shipping</dt><dd>To be confirmed</dd></div></dl><p class="flow-fine">Final shipping and tax details will appear before live payment. This sample checkout collects no payment or personal details.</p><p class="flow-fine"><a href="pages/policies/terms/index.html">Terms</a> · <a href="pages/policies/returns/index.html">Returns & replacements</a></p><p id="checkout-status" class="field-error" role="status"></p><button type="submit" class="button button--primary" data-checkout-next>Place sample order →</button><p class="flow-fine">Handcrafted frame · Ready to hang</p><a class="text-link" href="pages/contact/index.html">Need help?</a></aside></div></form>`;
};
