// Export only files needed to browse the prototype. No server or npm dependencies.
const fs=require('node:fs'),path=require('node:path');
const root=path.resolve(__dirname,'..'),out=path.join(root,'dist','site');
const {aliases}=require('../site-manifest.json');
const base='/'+(process.env.PAGES_BASE_PATH||'').replace(/^\/+|\/+$/g,'');
if(!/^\/[a-zA-Z0-9_./-]*$/.test(base)||base.split('/').includes('..'))throw Error('Invalid PAGES_BASE_PATH');
// This fixed output directory is generated by this script, never a source directory.
if(path.relative(root,out)!==path.join('dist','site'))throw Error('Invalid output directory');
if(fs.existsSync(out)){
 if(fs.lstatSync(out).isSymbolicLink())throw Error('Output cannot be a symbolic link');
 fs.rmSync(out,{recursive:true});
}
fs.mkdirSync(out,{recursive:true});
for(const file of ['index.html','site-map.html','.nojekyll','assets','shared','pages','product','shop-all','admin','docs/ADMIN-FINAL-FEATURES.md']){
 const dest=path.join(out,file);fs.mkdirSync(path.dirname(dest),{recursive:true});
 fs.cpSync(path.join(root,file),dest,{recursive:true,filter:source=>file!=='admin'||path.basename(source)!=='README.md'});
}
let redirects=0;
for(const [route,destination] of Object.entries(aliases)){
 if(route==='/')continue;
 const file=route.replace(/^\//,'')+'/index.html';
 if(fs.existsSync(path.join(out,file)))continue;
 const [target,query='']=destination.split('?');
 const relative=path.posix.relative(path.posix.dirname(file),target)+(query?'?'+query:'');
 const safe=relative.replaceAll('&','&amp;').replaceAll('"','&quot;');
 fs.mkdirSync(path.dirname(path.join(out,file)),{recursive:true});
 fs.writeFileSync(path.join(out,file),`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Opening Aalishaan Studio</title></head><body><p><a href="${safe}">Continue to Aalishaan Studio</a></p><script>const target=new URL(${JSON.stringify(relative)},location.href);new URLSearchParams(location.search).forEach((v,k)=>{if(!target.searchParams.has(k))target.searchParams.append(k,v);});target.hash=location.hash;location.replace(target.href);</script></body></html>`);
 redirects++;
}
const prefix=base==='/'?'':base;
const missing=fs.readFileSync(path.join(root,'pages/404.html'),'utf8').replace('<head>',`<head><base href="${prefix}/pages/">`);
fs.writeFileSync(path.join(out,'404.html'),missing);
// Hosting is for prototype review. Apply to every canonical and redirect page,
// without altering the approved source design or treating robots as access control.
function markPrototype(dir){
 for(const entry of fs.readdirSync(dir,{withFileTypes:true})){
  const file=path.join(dir,entry.name);
  if(entry.isDirectory())markPrototype(file);
  else if(entry.name.endsWith('.html')){
   const html=fs.readFileSync(file,'utf8').replace(/<meta\b[^>]*name=["']robots["'][^>]*>/gi,'');
   fs.writeFileSync(file,html.replace(/<head>/i,'<head><meta name="robots" content="noindex, nofollow">'));
  }
 }
}
markPrototype(out);
console.log(`Static site ready: dist/site (${redirects} static route redirects; 404 base ${base}).`);
