// M1 mobile review across all public routes and the first two content sections.
const {chromium}=require('playwright-core'),{createServer}=require('./serve.cjs');
const fs=require('node:fs'),assert=require('node:assert/strict');
(async()=>{const out='preview/mobile-m1';fs.mkdirSync(out,{recursive:true});const server=createServer();await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({channel:'chrome',headless:true}),base=`http://127.0.0.1:${server.address().port}/`,report={pages:[],errors:[],interactionChecks:[]};
 try{const context=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true}),page=await context.newPage();page.on('pageerror',e=>report.errors.push(e.message));page.on('response',r=>{if(r.url().startsWith(base)&&r.status()>=400)report.errors.push(r.status()+' '+r.url());});
  const go=async file=>{await page.goto(base+file);await page.evaluate(async()=>{await document.fonts.ready;await Promise.all([...document.images].filter(i=>i.getAttribute('src')).map(i=>{i.loading='eager';return i.decode();}));});await page.addStyleTag({content:'html{scroll-behavior:auto!important}'});};
  const pages=require('../site-manifest.json').pages.filter(p=>!p.file.startsWith('admin/'));
  for(const width of [320,390,430]){await page.setViewportSize({width,height:844});for(const p of pages){await go(p.file);const data=await page.evaluate(()=>{const h=document.querySelector('h1'),header=document.querySelector('.site-header'),hero=document.querySelector('main section'),rect=h?.getBoundingClientRect();const inputs=[...document.querySelectorAll('input:not([type=checkbox]):not([type=radio]):not([type=hidden]),select,textarea')].filter(e=>e.getBoundingClientRect().width>0&&getComputedStyle(e).visibility!=='hidden');return {title:h?.textContent,overflow:document.documentElement.scrollWidth>innerWidth,h1:rect?{left:rect.left,right:rect.right,top:rect.top,bottom:rect.bottom}:null,headerBottom:header?.getBoundingClientRect().bottom,smallInputs:inputs.filter(e=>parseFloat(getComputedStyle(e).fontSize)<16).map(e=>({id:e.id,name:e.name,font:getComputedStyle(e).fontSize})),heroHeight:hero?.getBoundingClientRect().height};});assert(!data.overflow,`${p.file} overflow ${width}`);assert(data.h1,`${p.file} missing h1`);assert(data.h1.left>=-1&&data.h1.right<=width+1,`${p.file} heading clipped at ${width}`);report.pages.push({file:p.file,width,...data});if(width===390){const name=p.file.replace(/[^a-z0-9]/gi,'-');await page.screenshot({path:`${out}/${name}-hero.png`});await page.evaluate(()=>{const second=document.querySelector('main .anatomy')||document.querySelectorAll('main > section')[1]||document.querySelectorAll('main section')[1];if(second)scrollTo(0,second.getBoundingClientRect().top+scrollY-90);else scrollTo(0,740);});await page.waitForTimeout(120);await page.screenshot({path:`${out}/${name}-second.png`});}}console.log('PASS public page layouts '+width+' px: '+pages.length+' pages');}
  await page.setViewportSize({width:390,height:844});await go('index.html');await page.locator('[data-open="mobile-nav"]').click();assert.equal(await page.locator('#mobile-nav').getAttribute('inert'),null);await page.locator('#mobile-nav [data-close]').click();const firstFaq=page.locator('#faq details').first(),initiallyOpen=await firstFaq.evaluate(e=>e.open);await firstFaq.locator('summary').click();assert.equal(await firstFaq.evaluate(e=>e.open),!initiallyOpen,'FAQ toggles from its initial state');await firstFaq.locator('summary').click();assert.equal(await firstFaq.evaluate(e=>e.open),initiallyOpen,'FAQ toggles back');
  await go('shop-all/index.html');await page.locator('.filters summary').click();const search=page.locator('#filter-form [name=q]');await search.fill('nothing-matches-this');assert(await page.locator('.empty-results').isVisible());await page.locator('[data-reset-filters]').click();assert.equal(await page.locator('#artwork-count').innerText(),'22 artworks');await search.fill('Lantern');assert.equal(await page.locator('#artwork-count').innerText(),'1 artwork');
  await go('product/index.html');await page.locator('input[name=frame][value=white]').check({force:true});await page.locator('#stage-button').count().then(async n=>{if(n)await page.locator('#stage-button').click();else await page.locator('.pd-stage__button').click();});assert(await page.locator('#lightbox').evaluate(d=>d.open));await page.keyboard.press('Escape');await page.locator('#delivery-pincode').fill('400001');await page.locator('#delivery-check button').click();await page.locator('#main-cta').click();await page.locator('#continue-checkout').click();await page.waitForURL('**/pages/checkout/index.html');await page.locator('#checkout-sample').click();await page.locator('[data-checkout-next]').click();await page.waitForURL('**/pages/order/demo/index.html');assert(await page.locator('#download-receipt').isVisible());
  report.interactionChecks.push('Touch-context menu, Home FAQ, catalogue filtering/no-match/reset, frame selection, lightbox, PIN check, add-to-cart and sample checkout.');
  // Short landscape phones must retain natural scrolling and an accessible hero/second section.
  for(const file of ['index.html','shop-all/index.html','product/index.html','pages/about/studio/index.html']){await page.setViewportSize({width:844,height:390});await go(file);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Landscape '+file);await page.screenshot({path:`${out}/landscape-${file.replace(/[^a-z0-9]/gi,'-')}.png`});}
  // Exact desktop card requested by the owner.
  await page.setViewportSize({width:1440,height:1000});await go('index.html');const card=page.locator('.route-card').nth(2);await card.scrollIntoViewIfNeeded();const fit=await card.locator('img').evaluate(i=>{const image=i.getBoundingClientRect(),media=i.parentElement.getBoundingClientRect();return {width:image.width,height:image.height,boxWidth:media.width,boxHeight:media.height,fit:getComputedStyle(i).objectFit};});assert(Math.abs(fit.width-fit.boxWidth)<2&&Math.abs(fit.height-fit.boxHeight)<2);assert.equal(fit.fit,'cover');await card.screenshot({path:out+'/desktop-art-styles-card.png'});report.desktopCard=fit;
  assert.deepEqual(report.errors,[]);fs.writeFileSync(out+'/review.json',JSON.stringify(report,null,2));console.log('PASS mobile interactions, landscape layouts and desktop art-style card.');console.log('Inputs below 16 px:',report.pages.filter(p=>p.smallInputs.length).map(p=>p.file+' @'+p.width+': '+p.smallInputs.length).join('\n')||'none');
 }catch(e){report.failure=e.stack;fs.writeFileSync(out+'/review.json',JSON.stringify(report,null,2));throw e;}finally{await browser.close();await new Promise(r=>server.close(r));}
})().catch(e=>{console.error(e);process.exitCode=1;});
