module.exports=()=>{
 const img=(src,alt)=>`<img src="${src}" alt="${alt}" loading="lazy" decoding="async">`;
 const section=(id,kicker,title,body,src,alt,reverse=false)=>`<section id="${id}" class="studio-section${reverse?' studio-section--reverse':''}"><div class="studio-image">${img(src,alt)}</div><div class="studio-copy"><span class="eyebrow">${kicker}</span><h2>${title}</h2>${body}</div></section>`;
 return `<section class="editorial-hero studio-hero studio-hero--r11"><div><span class="eyebrow">About the Studio</span><h1>Bring beauty into everyday life.</h1><p>The world is full of extraordinary beauty. We believe it deserves a permanent place in your home.</p><a class="button button--primary" href="#our-story">Meet the studio <span aria-hidden="true">↓</span></a></div></section>
 <nav class="studio-nav" aria-label="Explore the studio">${[['our-story','Our Story'],['our-artworks','Our Artworks'],['our-printing','Our Printing Process'],['our-frames','Our Frames'],['our-papers','Our Papers'],['our-purpose','Our Mission & Vision']].map(([id,title])=>`<a href="#${id}">${title}</a>`).join('')}</nav>
 ${section('our-story','Our Story','Some things deserve a second look.','<p>A branch after rain. A window catching the light. A harbour that feels like somewhere you have dreamed of.</p><p>Aalishaan Studio begins with moments like these. We curate artwork for the feeling it brings into a room—and the quiet pleasure of seeing it again tomorrow.</p>','assets/site/Card%202%20-%20Collection%20Image.png','Artwork from the Aalishaan Studio collections')}
 ${section('our-artworks','Our Artworks','Find the one that feels like you.','<p>Some walls ask for stillness. Others, a little adventure. Our collections move between landscapes, blossoms and imagined worlds, each with a story of its own.</p><p>We shape and curate our artwork using digital tools under professional creative direction. Each piece becomes an A2 archival print, made for the frame you choose.</p><a class="text-link" href="shop-all/index.html">Explore the artworks →</a>','assets/site/Card%203%20-%20Artstyle%20Image.png','A selection of visual traditions and art styles',true)}
 ${section('our-printing','Our Printing Process','From a feeling to a fine-art print.','<p>The image is only the beginning. Giclée printing brings its colour, fine lines and subtle transitions onto paper with care.</p><p>Our process uses 12-colour archival pigment inks on fine-art paper. Each artwork is printed and framed to order, ready for its place in your home.</p><div class="studio-facts"><span>Giclée printing</span><span>12-colour pigment inks</span><span>Made to order</span></div>','assets/site/GEN-04-Print%20Closeup.png','Close detail of a fine-art print')}
 ${section('our-frames','Our Frames','A frame that belongs to the story.','<p>The right frame gives an artwork presence. Ornately carved solid wood brings depth and detail, with a finish that changes how the piece feels.</p><p>Choose Antique Gold for warmth, Black for definition or White for a softer presence. Acrylic glazing and fitted hanging hardware complete the piece.</p><div class="studio-facts"><span>Antique Gold</span><span>Black</span><span>White</span></div>','assets/site/GEN%2001%20-%20Craft%20Detail%20-%20Gold%20Frame.png','Carved wood and antique gold frame detail',true)}
 ${section('our-papers','Our Papers','Beauty you can see. Character you can feel.','<p>Paper is part of the artwork. Its surface holds the colour, catches the light and lends the image a quiet depth.</p><p>We use Hahnemühle Museum Etching 350 gsm: natural-white cotton paper with a fine matt texture. A considered foundation for every A2 print.</p>','assets/site/GEN-02%20-%20Paper%20Closeup.png','The texture of fine-art paper')}
 <section id="our-purpose" class="studio-purpose"><span class="eyebrow">Our Mission and Vision</span><h2>More beauty in the everyday.</h2><div><article><h3>Our mission</h3><p>To bring thoughtfully curated artwork into everyday spaces—pieces that catch your eye, stir a feeling and make a room your own.</p></article><article><h3>Our vision</h3><p>Homes where art is part of living. Something you return to, connect with and enjoy, day after day.</p></article></div><a class="button button--primary" href="shop-all/index.html">Find your artwork <span aria-hidden="true">→</span></a></section>`;
};
